plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/styles/style-black.css

Just fixed the black theme dropdown CSS.

Add dropdown menu for Categories

---

plugins/dynamix/HelpButton.page
plugins/dynamix/include/DefaultPageLayout.php

This allows for help of individual settings by clicking on the specific
setting context.

Introduce context -sensitive help

---

plugins/dynamix/Eth0.page
plugins/dynamix/include/CheckPort.php
plugins/dynamix/scripts/netconfig

Also made width consistent with other pages

Fixed dropdown list may not open in tabbed view

---

plugins/dynamix/include/DeviceList.php
plugins/dynamix/include/Helpers.php

- fix bug in "my_scale" routine

Show array total size without fraction

---

plugins/dynamix.apcupsd/UPSdetails.page
plugins/dynamix.apcupsd/UPSsettings.page
plugins/dynamix.apcupsd/UPSsummary.page
plugins/dynamix.apcupsd/include/UPSstatus.php
plugins/dynamix.apcupsd/include/update.apcupsd.php
plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.plugin.manager/scripts/plugin
plugins/dynamix.plugin.manager/scripts/plugincheck
plugins/dynamix/scripts/diagnostics
plugins/dynamix/scripts/disk_log
plugins/dynamix/scripts/monitor
plugins/dynamix/scripts/notify
plugins/dynamix/scripts/spindowndelay
plugins/dynamix/scripts/statuscheck
plugins/dynamix/scripts/tail_log

Update copyright [3]

---

plugins/dynamix/include/DeviceList.php

For some reason the older version got included in the latest pull,
restored.

Restore latest version of DeviceList.php

---

plugins/dynamix/DashStats.page

If you're going to have a dashboard, you might as well make it easy to get to places you need to be...

Add in links to dashboard

---

plugins/dynamix/DashStats.page

To prevent browsers from scrolling to top of page when displaying / hiding more CPU / Network details

Remove href bookmarks on <a> elements

---

plugins/dynamix/Disk.page
plugins/dynamix/SecurityAFP.page
plugins/dynamix/SecurityNFS.page
plugins/dynamix/SecuritySMB.page
plugins/dynamix/Share.page
plugins/dynamix/ShareEdit.page
plugins/dynamix/include/ProtocolData.php
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

Adjusted widths to better fit small (1280) and wide (1920) screens

More refinements of Dynamix themes

---

logging.htm
plugins/dynamix.plugin.manager/include/ShowChanges.php
plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix/include/Feedback.php
plugins/dynamix/include/ParityHistory.php
plugins/dynamix/include/ReplaceKey.php
plugins/dynamix/include/SystemInformation.php
plugins/dynamix/include/TrialRequest.php
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-popup.css
plugins/dynamix/styles/dynamix-azure.css
plugins/dynamix/styles/dynamix-black.css
plugins/dynamix/styles/dynamix-gray.css
plugins/dynamix/styles/dynamix-white.css

Changed popup windows to higher contrast and the same for all themes

---

plugins/dynamix.docker.manager/include/CreateDocker.php

A never ending source of confusion with basically having Advanced appear on the Add/Edit Container screen twice

Change Advanced Settings to be More Settings

---

plugins/dynamix.plugin.manager/include/ShowPlugins.php
plugins/dynamix/SSLSettings.page
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-gray.css

- Use uppercase HTTP and HTTPS (sorry my network background)
- Reduce width of HTTP/HTTPS input boxes

Minor changes in SSL settings

---

plugins/dynamix/ArrayOperation.page

ArrayOperation code optimization

---

plugins/dynamix/scripts/diagnostics

Makes life easier with the reference rather than having to get the info via the syslog

Add in device identifier and unRaid assignment to SMART filename

---

plugins/dynamix/include/DashUpdate.php
plugins/dynamix/include/DeviceList.php
plugins/dynamix/scripts/monitor

194 = raw value is first choice
190 = raw value is second choice

Revised SMART temperature reading logic

---

plugins/dynamix.docker.manager/DockerSettings.page
plugins/dynamix/ArrayOperation.page
plugins/dynamix/Eth0.page
plugins/dynamix/EthX.page
plugins/dynamix/scripts/netconfig

+ Logical rearrangement of code sections

Fixed allow "permit format" when input file is selected

---

plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix/include/DeviceList.php
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

Please check if this correction is as intended.
- fsStatus is always present
- fsType is not present when parity or cache pool extra devices

Corrected empty file system display

---

plugins/dynamix.docker.manager/include/CreateDocker.php

Most notably "&" as in /mnt/user/this&that

Allow special characters in host paths

---

plugins/dynamix.docker.manager/DockerSettings.page

More enhancements on the Docker settings page:
1. Docker On/Off items better organized
2. Basic/Advanced items better organized
3. Code corrections
4. Expanded HELP text

Docker settings enhancements

---

plugins/dynamix.docker.manager/DockerSettings.page

Simplification of networks display

More enhancements in Docker settings

---

plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix/DashboardApps.page

Support Special Characters (&) in WebUI, Support & Project Context Menus

---

plugins/dynamix.docker.manager/DockerSettings.page
plugins/dynamix.plugin.manager/Update.page

Fixed regression error in Docker settings

---

plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix.docker.manager/include/ContainerManager.php
plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/include/DockerContainers.php
plugins/dynamix.docker.manager/javascript/docker.js
plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix.vm.manager/VMajax.php
plugins/dynamix.vm.manager/classes/VMMachines.php
plugins/dynamix.vm.manager/classes/VMManager.php
plugins/dynamix.vm.manager/classes/libvirt_helpers.php
plugins/dynamix.vm.manager/javascript/vmmanager.js
plugins/dynamix/DashboardApps.page
plugins/dynamix/include/DashboardApps.php

Add rotating animation when starting or stopping a container or vm

Load docker and vm lists in background to speed up rendering

---

plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix.docker.manager/include/DockerContainers.php
plugins/dynamix.docker.manager/include/DockerUpdate.php
plugins/dynamix.docker.manager/javascript/docker.js
plugins/dynamix.plugin.manager/Plugins.page
plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix.vm.manager/include/VMManager.php
plugins/dynamix.vm.manager/javascript/vmmanager.js
plugins/dynamix/DashboardApps.page
plugins/dynamix/include/PageBuilder.php

Sort pages natural, so numbers are in correct order, e.g. 10 is after 9

Minor changes

---

plugins/dynamix.apcupsd/UPSdetails.page
plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix.plugin.manager/Plugins.page
plugins/dynamix.plugin.manager/Update.page
plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix/Browse.page
plugins/dynamix/DashStats.page
plugins/dynamix/DeviceAttributes.page
plugins/dynamix/DeviceCapabilities.page
plugins/dynamix/DeviceIdentify.page
plugins/dynamix/DiskList.page
plugins/dynamix/NotificationsArchive.page
plugins/dynamix/SSLSettings.page
plugins/dynamix/Selftest.page
plugins/dynamix/ShareList.page
plugins/dynamix/SysDevs.page
plugins/dynamix/include/DashboardApps.php

follows now the same logic as system information

Corrected memory display on Dashboard page

---

plugins/dynamix.docker.manager/include/CreateDocker.php

Hole allows arbitrary execution of bash commands on host

Plug Security Hole In Docker Template PostArgs

---

plugins/dynamix.docker.manager/include/CreateDocker.php

Revert "Plug Security Hole In Docker Template PostArgs"

---

plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/javascript/vmmanager.js

- changed DETACH is available when VM is running
- default bus to VirtIO
- minor layout changes
Still detach operation fails with "Unable to attach disk"
@eschultz: Something with libvirt itself which goes wrong?

VMmachine updates

---

plugins/dynamix.docker.manager/include/CreateDocker.php

Fix Create Docker php warning

---

plugins/dynamix.docker.manager/include/CreateDocker.php

+ little rewrite to PHP7 syntax

Restore Apply button to previous behavior

---

plugins/dynamix/scripts/diagnostics

Suggestions from this thread: https://lime-technology.com/forums/topic/70460-how-to-read-diagnostics/
Moved log capture to very end so its as current as possible

Diagnostic improvements

---

plugins/dynamix.plugin.manager/Plugins.page
plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php
plugins/dynamix.vm.manager/templates/XML_Expert.form.php
plugins/dynamix/DashboardApps.page
plugins/dynamix/DisplaySettings.page
plugins/dynamix/Syslinux.page
plugins/dynamix/UserAdd.page
plugins/dynamix/UserEdit.page
plugins/dynamix/include/Boot.php
plugins/dynamix/include/CryptoBenchmark.php
plugins/dynamix/include/Feedback.php
plugins/dynamix/include/ReplaceKey.php
plugins/dynamix/include/TrialRequest.php

Wrap all CSS/JS calls in autov()

---

plugins/dynamix.vm.manager/VMSettings.page
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix/CPUvms.page
plugins/dynamix/DeviceInfo.page
plugins/dynamix/DiskSettings.page
plugins/dynamix/include/UpdateOne.php
plugins/dynamix/include/update.parity.php

- changed Areca to SAS format
- added HP cciss
- fixed global controller selection

Miscellaneous fixes and updates

---

plugins/dynamix/scripts/diagnostics

lol  Whenever I look through someone's diagnostics, I always think that they have a porn addiction

Change anonymized email address

---

plugins/dynamix/scripts/diagnostics

More generalized.  Actually itemize which disks the share is stored on.

Diagnostics Update to #408

---

plugins/dynamix/include/SystemInformation.php

Hidden by default and showing when **Memory** is clicked.

Add per DIMM information toggle

---

plugins/dynamix.apcupsd/UPSsummary.page
plugins/dynamix.plugin.manager/include/ShowPlugins.php
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

And allow use of the new unRaid icons

Allow plugins to use font awesome for icons

---

plugins/dynamix.apcupsd/UPSsummary.page
plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix.docker.manager/event/docker_started/docker_load_start
plugins/dynamix.docker.manager/event/stopping_docker/docker_load_stop
plugins/dynamix.docker.manager/include/DockerContainers.php
plugins/dynamix.docker.manager/include/UpdateConfig.php
plugins/dynamix.docker.manager/javascript/docker.js
plugins/dynamix.plugin.manager/Plugins.page
plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/javascript/vmmanager.js
plugins/dynamix/DashStats.page
plugins/dynamix/include/DashboardApps.php
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css
plugins/dynamix/styles/jquery.switchbutton.css

Dashboard: more updates and corrections

---

plugins/dynamix/include/NotificationAgents.xml

verbose script execution, fix variable assignment, exit upon false chatid retrieval, replace cat in command substitution, mute curl

telegram notification agent bug fixes

---

plugins/dynamix/include/DefaultPageLayout.php

Change to keep srrary operation status visible when it is paused, but with "(Paused)" added to the status message

Keep status visible for paused array operations

---

plugins/dynamix/DashStats.page

Fixes https://forums.unraid.net/bug-reports/stable-releases/custom-icon-on-dashboard-r583/

Fix custom case png not surviving reboot

---

plugins/dynamix.docker.manager/include/CreateDocker.php

See here: https://forums.unraid.net/topic/38619-docker-template-xml-schema/page/2/?tab=comments#comment-773589
Code though has to stay (albeit hidden) so that what CA does enter in for it is saved in the template.

dockerMan - Deprecate TemplateURL

---

plugins/dynamix.plugin.manager/scripts/PluginAPI.php

Some authors have listed a plugin URL that is subject to redirection

Plugin Helpers: Follow redirects on downloads

---

plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

My OCD just noticed that the spinner within CA would display underneath the donate buttons

Ensure spinner always on top

---

logging.htm
login.php
plugins/dynamix.docker.manager/include/ContainerSize.php
plugins/dynamix.docker.manager/log.htm
plugins/dynamix.plugin.manager/include/ShowChanges.php
plugins/dynamix/include/Boot.php
plugins/dynamix/include/CryptoBenchmark.php
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/include/Feedback.php
plugins/dynamix/include/ParityHistory.php
plugins/dynamix/include/ReplaceKey.php
plugins/dynamix/include/SelectCase.php
plugins/dynamix/include/SystemInformation.php
plugins/dynamix/include/TrialRequest.php
update.htm

If a page is loaded via https, prevent it from loading resources via http

CSP: block-all-mixed-content

---

plugins/dynamix/include/DefaultPageLayout.php

Drives me nuts having to click the "x", as so used to CA allowing an outside click.  Only allows an outside click if when closing the window nothing happens

Allow outside click to close popups

---

login.php

Maybe I'm just paranoid, but with ports open, a reverse proxy thru unraid.net, I wouldn't mind seeing any and all login attempts to the server

Log webUI login attempts

---

plugins/dynamix.docker.manager/include/GetContainerSize.php

https://forums.unraid.net/topic/85297-docker-image-utilization/?tab=comments#comment-791378

Don't display error if docker log files manually deleted

---

plugins/dynamix.plugin.manager/scripts/PluginAPI.php
plugins/dynamix.vm.manager/VMSettings.page
plugins/dynamix/CPUisol.page
plugins/dynamix/CPUvms.page
plugins/dynamix/include/DefaultPageLayout.php

Revert "Preserve reboot notices across GUI pages"

---

plugins/dynamix.docker.manager/include/CreateDocker.php

@limetech Also did a PR for the sysdream template to reflect this

dockerMan: Add Security as a category

---

plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/include/Helpers.php

Effectively only used when still using docker template repositories (ugh).  CA handles this normally and blacklists violations

dockerMan: Security enhancements

---

plugins/dynamix/include/Translations.php

Remove any translations that attempt to inject code into the OS

Multi-language Support

---

plugins/dynamix.plugin.manager/PluginHelpers.page

Regression error after multi-language updates

Plugin Update banner wouldn't display change logs

---

plugins/dynamix/include/LanguageReset.php

Handle Situation on switching languages if the user has never changed a setting in the OS

Multi Language Support

---

plugins/dynamix/SysDevs.page
plugins/dynamix/include/SysDevs.php
plugins/dynamix/include/update.vfio-pci-cfg.php

SysDevs overhaul with vfio-pci.cfg binding

---

plugins/dynamix/include/DeviceList.php

Multi cache pool support

---

plugins/dynamix.docker.manager/DockerSettings.page
plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/scripts/docker_rm
plugins/dynamix/include/SystemInformation.php
plugins/dynamix/scripts/diagnostics

Added btrfs info for all pools in diagnostics

Multi-cache pool support

---

plugins/dynamix.apcupsd/apcupsd.notify
plugins/dynamix.docker.manager/scripts/dockerupdate.php
plugins/dynamix.plugin.manager/scripts/languagecheck
plugins/dynamix.plugin.manager/scripts/plugincheck
plugins/dynamix.plugin.manager/scripts/unraidcheck
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/scripts/monitor
plugins/dynamix/scripts/notify
plugins/dynamix/scripts/statuscheck

Allow notifications to link to pages in the GUI.
Pet Peeve: Clicking on the browser notification doesn't do anything.  This allows for clicking on the notification to actually take you to where you need to be to handle the notification.

Support links on notifications

---

plugins/dynamix.docker.manager/DockerSettings.page
plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/javascript/addDocker.js
plugins/dynamix/ArrayOperation.page
plugins/dynamix/CPUvms.page
plugins/dynamix/CacheDevices.page
plugins/dynamix/DashStats.page
plugins/dynamix/DeviceInfo.page
plugins/dynamix/DisplaySettings.page
plugins/dynamix/Eth0.page
plugins/dynamix/FlashInfo.page
plugins/dynamix/Language.page
plugins/dynamix/ManagementAccess.page
plugins/dynamix/NetworkRules.page
plugins/dynamix/NewPerms.page
plugins/dynamix/NotificationsArchive.page
plugins/dynamix/RoutingTable.page
plugins/dynamix/ShareEdit.page
plugins/dynamix/SmtpSettings.page
plugins/dynamix/UserAdd.page
plugins/dynamix/UserEdit.page
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/include/TrialRequest.php

Primarily affects French translations.  Rather than adjusting the code on a case by case basis, apply the fixes across the board for future translations.
Current Unraid versions show & apos; when stopping the array etc from Main, dashboard etc and probably other locations when in French
Visual distraction only, and doesn't necessarily need to be merged for beta26
This is a pro-active continuation of PR #741

Fix &apos; appearing in swal alerts

---

plugins/dynamix/MoverSettings.page

https://forums.unraid.net/bug-reports/prereleases/690-beta25-unable-to-schedule-a-parity-check-r1063/

Fix not able to change parity check schedule if no cache pool present

---

plugins/dynamix/ShareEdit.page

https://forums.unraid.net/bug-reports/stable-releases/683-share-name-validation-r1060/

Disallow "?" in share names

---

plugins/dynamix/scripts/statuscheck

Fix missing quote on status check

---

plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix.docker.manager/include/DockerContainers.php
plugins/dynamix.docker.manager/javascript/docker.js

https://forums.unraid.net/topic/98034-include-logs-in-the-docker-tabs-dropdown-just-like-the-dashboard-docker-dropdown-has-it/

Changed: Consistency between dashboard and docker on accessing logs

---

plugins/dynamix/styles/dynamix-azure.css
plugins/dynamix/styles/dynamix-black.css
plugins/dynamix/styles/dynamix-gray.css
plugins/dynamix/styles/dynamix-white.css

If there's a better place to put this please let me know.

fix: jGrowl covering buttons

---

plugins/dynamix/NewPerms.page
plugins/dynamix/scripts/newperms

Much easier in PHP to handle multi-cache pools

New Perms: Support multi-cache pools

---

plugins/dynamix.docker.manager/DockerContainers.page

Helps with https://forums.unraid.net/topic/42056-port-range-mapping-in-docker-container-setup-bridge-mode/?tab=comments#comment-911251

dockerMan: Allow readmore in advanced view

---

plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/styles/dynamix-azure.css
plugins/dynamix/styles/dynamix-black.css
plugins/dynamix/styles/dynamix-gray.css
plugins/dynamix/styles/dynamix-white.css

https://forums.unraid.net/bug-reports/prereleases/690-beta35-close-all-notifications-button-no-longer-working-when-notifications-are-set-to-the-bottom-lr-of-the-screen-r1129/

Fix unable to dismiss all notifications when on bottom

---

plugins/dynamix.docker.manager/DockerSettings.page
plugins/dynamix/include/DashboardApps.php

https://forums.unraid.net/bug-reports/prereleases/690-beta-35-dashboard-ui-broken-for-docker-vms-r1126/

Fix Started VMs not appearing in dashboard

---

plugins/dynamix/DashStats.page

Change Icon for Motherboard Info from cog (settings) to info

---

plugins/dynamix.docker.manager/include/CreateDocker.php

Pet peeve of mine, and also https://forums.unraid.net/topic/101369-feature-request-docker-startcreation-handling-improvement/
Doesn't affects running containers.  They will either be stopped or started depending upon their last state prior to editing.

dockerMan: Selectable start upon install

---

plugins/dynamix/include/local_prepend.php

Logging in with Safari works again 🥞

Fix: properly set samesite cookie

---

plugins/dynamix/SysDevs.page

Prevent incorrect warnings on systems with no IOMMU groups

SysDevs - fix warn if leave page without saving

---

plugins/dynamix/include/SysDevs.php

https://forums.unraid.net/bug-reports/stable-releases/690-parsing-error-in-system-devices-vfio-pci-config-r1298/?tab=comments#comment-13324

System Devices fix display aberration

---

plugins/dynamix/Diagnostics.page

Diagnostics: Prevent double clicks on download button

---

plugins/dynamix/styles/dynamix-white.css

Fix syntax in the dynamix white css

Fix CSS span.select background-color

---

plugins/dynamix/scripts/monitor

https://forums.unraid.net/bug-reports/stable-releases/disk-utilization-colors-not-consistent-from-dashboard-to-main-r1296/

Fix default usage thresholds not sending notification

---

plugins/dynamix/styles/jquery.sweetalert.css

Fix element `.sa-icon.sa-success` border color

Fix .sweet-alert .sa-icon color

---

plugins/dynamix/styles/context.standalone.css

Removal of `*` in CSS file, good?

Fixes * in the CSS

---

plugins/dynamix/ManagementAccess.page

@bergware, since we are starting to use more and more sprintf within the UI, can I suggest that we incorporate the sprintf library from CA (javascript/libraries.js) as it's a complete implementation

Validate WebGUI ports before applying

---

plugins/dynamix/include/SelectCase.php

Update alert text

---

plugins/dynamix/ArrayDevices.page
plugins/dynamix/ArrayOperation.page
plugins/dynamix/nchan/disk_load

Nchan start/stop foundation

---

plugins/dynamix.docker.manager/include/CreateDocker.php

dockerMan: remove HTML from descriptions

---

plugins/dynamix.my.servers/include/state.php

upc and pop-up no longer use this specific apikey

refactor statephp

---

plugins/dynamix/include/DefaultPageLayout.php

Form must set the opt-in class "js-confirm-leave"

add leave confirmation when form has changed without applying

---

plugins/dynamix/scripts/diagnostics

Summary of useCacheSettings and where the share exists.  Everything I want to see at a glance.

Diagnostics: Add share summary

---

plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/include/Helpers.php

Don't hold up any RC because of this.

Docker: Support CA tag <Requires>

---

plugins/dynamix/include/SysDevs.php

Please find PR for addtiton of the physical port to usb lists in SysDevs,
ljm42 has already seen a preview, but let me know any feedback.

System devices additions

---

plugins/dynamix/include/SysDevs.php

Fix issue with column spaces for larger usb port values.

Fix column formating if port size is greater than 7 chars in SysDevs.php

---

plugins/dynamix/include/UpdateDNS.php

- should only go out to internet if a LE cert has been provisioned.
- added verbose mode (-v)
- minor code cleanup

Improvements to UpdateDNS

---

plugins/dynamix.docker.manager/include/Helpers.php

add extra environment variables to the container

Add HOST_HOSTNAME and HOST_CONTAINERNAME env vars

---

plugins/dynamix.docker.manager/include/Helpers.php

As per suggestion from @bergware

Change setting of HOST_xxxxxx env vars

---

plugins/dynamix/scripts/diagnostics

Add details to aid troubleshooting the HTTP and HTTPS urls for this server

Diagnostics: add url details

---

plugins/dynamix/include/UpdateDNS.php

* move verbose output to a separate function
* anonymize verbose output by default
* check for DNS Rebind Protection
* disable cache if DDNS does not resolve correctly

refactor UpdateDNS.php

---

plugins/dynamix/ArrayOperation.page

This reverts commit 5e3a7bb33d6be1395df75e80180c132495aa3cbe.

Revert "Move Start button below encryption field"

---

plugins/dynamix.docker.manager/include/DockerClient.php
plugins/dynamix.my.servers/include/myservers2.php
plugins/dynamix/ManagementAccess.page
plugins/dynamix/SyslogSettings.page
plugins/dynamix/WG0.page
plugins/dynamix/include/ProvisionCert.php
plugins/dynamix/include/UpdateDNS.php
plugins/dynamix/include/Wrappers.php

protocol defaults to ipv4 in case of ipv4 + ipv6

Expand ipaddr() with protocol; selection

---

plugins/dynamix.docker.manager/DockerContainers.page
plugins/dynamix/ArrayOperation.page
plugins/dynamix/DashStats.page
plugins/dynamix/Diagnostics.page
plugins/dynamix/Eth0.page
plugins/dynamix/WG0.page
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/nchan/parity_list

Use multiplexed channels and add error reporting

Nchan improvements

---

plugins/dynamix/ArrayOperation.page

Previous PR had this removed, but now it is properly coded.

Parity check: re-introduce Done button when finished

---

plugins/dynamix/ArrayOperation.page
plugins/dynamix/DashStats.page
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/include/Helpers.php
plugins/dynamix/include/ParityHistory.php
plugins/dynamix/include/ReloadPage.php
plugins/dynamix/nchan/device_list
plugins/dynamix/nchan/parity_list
plugins/dynamix/nchan/update_2
plugins/dynamix/scripts/monitor
plugins/dynamix/scripts/parity_control
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

- Separate Parity-Sync and Data-Rebuild as individual actions
- Add parity operation action to history view
- Correct calculations for data-rebuild smaller than parity
- Add disk clear action
- Use Nchan updates for copying/clearing progress
- CSS adjustment in SMART attributes
- Show additional buttons in Array Stopped state
- Textual enhancements
- Sync Dashboard view with Main view

Parity operation enhancements

---

plugins/dynamix/DeviceInfo.page

changed default ratio from 30 to 50

BTRFS balance recommendation enhancement

---

plugins/dynamix/include/UpdateDNS.php

Synchronize with UpdateDNS from My Servers plugin

UpdateDNS - reduce unnecessary rebind test checks

---

plugins/dynamix/include/Helpers.php
plugins/dynamix/include/PageBuilder.php

To avoid naming confusion, keep names in lowercase

Do not capitalize first character of device name

---

plugins/dynamix/SmtpSettings.page

ref: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

Update Outlook/Hotmail smtp settings

---

plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

Better suited for people with color impairment

Adjusted row highlighting on main and shares page

---

plugins/dynamix/include/NotificationAgents.xml

Sorry for the bothering and the lack of tests, and it should be the last pr about it.

fix minor errors in Pushplus & ServerChan agents

---

plugins/dynamix/Syslog.page
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-gray.css

- Better support for Firefox
- Move utilization and notification indicators to the right

Updated azure/gray themes

---

plugins/dynamix.plugin.manager/scripts/plugin

Plugin system update

---

plugins/dynamix/api/api.txt

This folder contains scripts and other files related to API functionality. To keep a distinct separation between regular GUI resources and API resources, which can be used by entities outside the GUI domain.

Create API folder

---

plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/include/VMajax.php
plugins/dynamix.vm.manager/include/libvirt.php
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/templates/Custom.form.php

Add boot order to GUI.
Initially show order.

Add boot order to GUI and CD hot plug function

---

plugins/dynamix.plugin.manager/scripts/multiplugin

Fix plugin multi updates

---

plugins/dynamix.vm.manager/include/libvirt.php
plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Enable boot order update via template.

Enable Update of Boot Order in GUI Template.

---

plugins/dynamix.vm.manager/include/libvirt.php
plugins/dynamix.vm.manager/templates/Custom.form.php

Include 9P and Virtiofs(Virtiofs only for Windows)
Memory backing Needs to be reviewed.

Update VM Share GUI Options

---

plugins/dynamix/include/update.wireguard.php

Users are advised to regenerate the WG configs.

WireGuard: add explicit interface name in routing

---

plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix.vm.manager/include/VMajax.php
plugins/dynamix.vm.manager/include/libvirt.php
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Fixes for CD Hotplug.
Add Support for NVME boot order.

CD Hotplug bug fix and boot order for nvme pci passthru

---

plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/templates/Custom.form.php

Add Unraid share drop down, allowing selection of a Share to populate the path and tag.
When select path and tag are hidden
But when reopening the VM for update will default to Manual and show path and tag.

Add Unraid Share Mapping.

---

plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Clarify help text.

---

plugins/dynamix.vm.manager/templates/Custom.form.php

Change fields to disable

---

plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Test to see if guest agent is installed before calling domain_qemu_agent_command to avoid following error in logs.
error : qemuDomainAgentAvailable:8411 : Guest agent is not responding: QEMU guest agent is not connected
Update text to say if guest is not running or guest agent not installed.
Fix hotplug  USB if guest is running.

Template update hotplug fix and Guest Agent Test

---

plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Fix for CPU reverting to passthru.
Can only check for Intel CPUs would need validation for AMD.

Fix changing from passthru to custom CPU.

---

plugins/dynamix.plugin.manager/scripts/plugin

Also set IPv4 as the preferred protocol.  This may help with cdn downloads.

Adjust the wget parameters to keep it from indefinitely hanging.

---

plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/include/VMajax.php
plugins/dynamix.vm.manager/include/libvirt.php
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/javascript/vmmanager.js
plugins/dynamix/include/DashboardApps.php

HyperV option Fix. 
Needs additional testing on Feature options.

Update HyperV Option changes.

---

plugins/dynamix.vm.manager/include/libvirt.php
plugins/dynamix.vm.manager/include/libvirt_helpers.php
plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Add boot order field to USB devices
Add OS boot setting for USB Boot.

Add boot order for USB and USB Boot option

---

plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Add Boot Order field clear if USB Boot selected.

---

plugins/dynamix.plugin.manager/scripts/plugin
plugins/dynamix/ParityCheck.page
plugins/dynamix/ShareEdit.page
plugins/dynamix/include/ShareList.php

Initial installation of Unraid now defaults to non-correcting.

Fix default on initial install; preserve error on first plugin wget; show pool not defined when share pool is not a defined pool.

---

plugins/dynamix.vm.manager/templates/Custom.form.php
plugins/dynamix.vm.manager/templates/LibreELEC.form.php
plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Still need to add PCI type check.

Set correct values when edit for USBBoot and correct Share Selection.

---

plugins/dynamix.plugin.manager/scripts/showchanges
plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/include/StartCommand.php
plugins/dynamix/scripts/feedback
plugins/dynamix/scripts/parity_history
plugins/dynamix/scripts/select_case
plugins/dynamix/scripts/system_information
plugins/dynamix/scripts/wg_config

Informational functions which call "openChanges" are now processed using post requests, this solves the issue that sometimes an empty window is displayed.

Fixes issue that sometimes information window opens empty

---

plugins/dynamix.vm.manager/templates/Custom.form.php

Add support for PCI Type 02xx as well as 0108

Allow Network PCI devices to have boot order.

---

plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/include/VMajax.php
plugins/dynamix.vm.manager/spice.html
plugins/dynamix/include/DashboardApps.php

Change title to say VM name on host: x.x.x.x

Spice Bug fix for users with non standard GUI ports defined.

---

plugins/dynamix.vm.manager/include/VMMachines.php
plugins/dynamix.vm.manager/include/libvirt.php

Create __construct() function.
Fix typo for macs should be $macs
Fix logfile size
Remove Bus, working on fix.

Initial Fix PHP 8

---

plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix.vm.manager/include/libvirt.php

<?#$color = strpos($msg, "rror:")!==false ? 'red-text':'green-text'?> Still need to find a fix for this, but remarked out to get it working for now.

Additional VM Manager PHP fixes

---

plugins/dynamix.docker.manager/include/CreateDocker.php
plugins/dynamix.docker.manager/include/DockerClient.php
plugins/dynamix.docker.manager/include/Helpers.php
plugins/dynamix.vm.manager/VMMachines.page
plugins/dynamix/ArrayDevices.page
plugins/dynamix/BootDevice.page
plugins/dynamix/CacheDevices.page
plugins/dynamix/DiskList.page
plugins/dynamix/OpenDevices.page
plugins/dynamix/ShareList.page
plugins/dynamix/include/DiskList.php
plugins/dynamix/include/ShareList.php
plugins/dynamix/include/UpdateTwo.php
plugins/dynamix/include/Wrappers.php
plugins/dynamix/nchan/device_list
plugins/dynamix/nchan/update_2
plugins/dynamix/scripts/diagnostics
plugins/dynamix/scripts/monitor
plugins/dynamix/scripts/select_case
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

This error prevents the selection of another case

Miscellaneous fixes

---

plugins/dynamix/scripts/diagnostics

- created BEGIN and END comment for third party plugins
- added LXC thridparty plugin to diagnostics
- added iSCSI-Target thridparty plugin to diagnostics
- added iSCSI-Initiator thridparty plugin to diagnostics

overhaul from third party plugins diagnostics and additions

---

plugins/dynamix.docker.manager/include/DockerClient.php

Not critical, just for a clean code 👍

fix(docker): update header indent

---

plugins/dynamix.plugin.manager/scripts/plugin

... for debugging purposes maybe..? ;)

[plugin] Include the actual command, being executed

---

plugins/dynamix/include/DefaultPageLayout.php
plugins/dynamix/styles/default-azure.css
plugins/dynamix/styles/default-black.css
plugins/dynamix/styles/default-gray.css
plugins/dynamix/styles/default-white.css

- Menu items without messages are disabled

Notifications: single icon only

---

plugins/dynamix/include/update.vfio-pci-cfg.php

- Allow all text
- Return correct state

Update VFIO: fix regression errors

---

plugins/dynamix/scripts/newperms

Only /mnt/disk or /mnt/user is accepted

newperms: added path check to restrict the operation

---

languages/en_US/helptext.txt
plugins/dynamix/Eth0.page
plugins/dynamix/EthX.page

- For interfaces other then eth0

Network settings: fix bug in description field

---

emhttp/plugins/dynamix.vm.manager/VMMachines.page
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/include/CPUset.php

Fix issues with VM page loads if users have removed vcpu pinning.
in_array fails due to vcpu being false and not an array.

Fix VM page load issue

---

etc/rc.d/rc.library.source
etc/rc.d/rc.ntpd
etc/rc.d/rc.sshd

NTP: exclude WG tunnels and user defined interfaces
NTP: add interface name in config
SSH: add interface name in config

rc updates

---

emhttp/plugins/dynamix/SecurityNFS.page

Users are requesting more room on the input line for their NFS rules.

Allow more room on input line for NFS rules.

---

emhttp/plugins/dynamix/scripts/feedback

Accidentally pushed refactor of this file.
Reverting via correct workflow with a PR.

revert: feedback script to old format

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Retrieve password during update to keep, Currently you have to re-enter.

Retain VNC password during update.

---

emhttp/plugins/dynamix/scripts/diagnostics

Add the previous version and upgrade date to the version txt file if the /boot/previous/changes.txt file is found.

Add previous Unraid version to diagnostics version txt file.

---

emhttp/plugins/dynamix.docker.manager/DockerSettings.page
emhttp/plugins/dynamix/scripts/diagnostics

The vfat file system will not give us the date from the file when the upgrade was done.

Remove upgrade date.

---

emhttp/plugins/dynamix/include/SysDriversHelpers.php

Reduce number of tar packages tested.

System Drivers

---

emhttp/plugins/dynamix/scripts/diagnostics
etc/rc.d/rc.inet1

This should "solve" hopefully the macvlan call traces

Network: do not use promiscuous mode for bridging

---

emhttp/plugins/dynamix/SysDrivers.page
emhttp/plugins/dynamix/include/SysDrivers.php
emhttp/plugins/dynamix/include/SysDriversHelpers.php

Add remove button and confirmation
Fix sort issues by updating cells
Code tidy

Sysdrivers: Updates

---

emhttp/plugins/dynamix.docker.manager/DockerSettings.page
emhttp/plugins/dynamix.docker.manager/scripts/rebuild_container
emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix/include/SysDrivers.php
etc/rc.d/rc.docker
etc/rc.d/rc.inet1
etc/rc.d/rc.libvirt

networking: use new macvtap network instead of macvlan

---

etc/rc.d/rc.docker
etc/rc.d/rc.inet1

Make MAC addresses unique per system

vhost and shim network: assign predefined MAC address

---

etc/rc.d/rc.docker
etc/rc.d/rc.inet1
etc/rc.d/rc.wireguard

Connection to Internet is interrupted at startup and Wireguard docker VPN is configured

rc.wireguard: fix regression bug

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.vm.manager/VMSettings.page
sbin/qemu

Create options to disable VM auto start.

Create VM autostart disable option

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.vm.manager/VMSettings.page
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/scripts/VMAjaxCall.php
emhttp/plugins/dynamix.vm.manager/scripts/VMClone.php

PHP Fixes
Change to Disable option text for Autostart

PHP and Code tidy fixes

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/include/SysDrivers.php
emhttp/plugins/dynamix/include/SysDriversHelpers.php

Add support for Multifunction
<hostdev mode='subsystem' type='pci' managed='yes'>
<driver name='vfio'/>
<source>
<address domain='0x0000' bus='0x0d' slot='0x00' function='0x0'/>
</source>
<address type='pci' domain='0x0000' bus='0x20' slot='0x0d' function='0x0' multifunction='on'/>
</hostdev>
<hostdev mode='subsystem' type='pci' managed='yes'>
<driver name='vfio'/>
<source>
<address domain='0x0000' bus='0x0d' slot='0x00' function='0x1'/>
</source>
<address type='pci' domain='0x0000' bus='0x20' slot='0x0d' function='0x1'/>
</hostdev>
Multifunction will use format for a fixed bus i.e. 0x20 and the slot will be the bus of the physical PCI device.

VM multifunction support

---

emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
emhttp/plugins/dynamix.vm.manager/sheets/VMMachines.css

Add IP addresses to title on name.
Font is smaller than shown.
Font for Graphics will be as this capture.

Show all graphics cards

---

emhttp/plugins/dynamix/include/SysDrivers.php

only add space if version number from module is found

System Drivers: Just for the looks

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Add option to set Migration to off or on. Default is on for new VMs

VM  template enhancements for windows vms

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php

Something may have changed in Libvirt or QEMU.

Fix to multifunction which fails with non zero slot on beta21

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php

Slot has to be > 1 for pc and 0 for q35

Additional multifunction changes

---

emhttp/plugins/dynamix/Syslog.page
emhttp/plugins/dynamix/scripts/diagnostics

Also needs changes to rc.M from https://github.com/unraid/webgui/pull/1449/

Backport to 6.12 - Improved handling of USB-mirrored syslogs

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Support for QEMU args have been added to the template.

QEMU cmdline

---

etc/rc.d/rc.local

Rendered obsolete by https://github.com/unraid/webgui/pull/1493
Finally :)

Unlimited Width Plugin Obsolete

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/sheets/AddVM.css
emhttp/plugins/dynamix.vm.manager/sheets/UpdateVM.css
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix.vm.manager/templates/LibreELEC.form.php
emhttp/plugins/dynamix.vm.manager/templates/OpenELEC.form.php

Add support to change clock offset and clock timers from the GUI.

Add offset and timer support

---

emhttp/plugins/dynamix.vm.manager/spice.html
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Update text from VNC to VM Console for titles and placeholders

Fix spice autoconnect

---

emhttp/plugins/dynamix.vm.manager/spice.html
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Update VNC to VM Console for place holders and titles.

Backport 6.12 -> Fix spice auto connect

---

emhttp/plugins/dynamix/Console.page
emhttp/plugins/dynamix/scripts/console
etc/rc.d/rc.keymap
etc/rc.d/rc.local
etc/rc.d/rc.setterm

- Create page for Local Console
- Create console script
- Create rc.keymap and modify default ot be compatible with local console settings
- Change rc.setterm to be compatible with local console settings
- Change rc.local to be compatible with persistent bash history

Local Console settings

---

emhttp/plugins/dynamix/ArrayDevices.page
emhttp/plugins/dynamix/include/ToggleState.php
emhttp/plugins/dynamix/nchan/device_list

Based on implementation for beta 23

New device spin up/down logic

---

emhttp/plugins/dynamix.my.servers/Registration.page
emhttp/plugins/dynamix.my.servers/include/myservers1.php
emhttp/plugins/dynamix.my.servers/include/myservers2.php
emhttp/plugins/dynamix.my.servers/include/reboot-details.php
emhttp/plugins/dynamix.my.servers/include/state.php
emhttp/plugins/dynamix.my.servers/include/translations.php
emhttp/plugins/dynamix.plugin.manager/Downgrade.page
emhttp/plugins/dynamix.plugin.manager/Update.page
emhttp/plugins/dynamix/include/DefaultPageLayout.php
emhttp/plugins/dynamix/scripts/flash_backup
emhttp/plugins/dynamix/styles/default-azure.css
emhttp/plugins/dynamix/styles/default-black.css
emhttp/plugins/dynamix/styles/default-gray.css
emhttp/plugins/dynamix/styles/default-white.css

Revert "6.12.5 – upc feedback & fixes"

---

emhttp/plugins/dynamix.my.servers/Registration.page
emhttp/plugins/dynamix.my.servers/data/server-state.php
emhttp/plugins/dynamix.my.servers/include/myservers1.php
emhttp/plugins/dynamix.my.servers/include/myservers2.php
emhttp/plugins/dynamix.my.servers/include/reboot-details.php
emhttp/plugins/dynamix.my.servers/include/state.php
emhttp/plugins/dynamix.my.servers/include/translations.php
emhttp/plugins/dynamix.plugin.manager/Downgrade.page
emhttp/plugins/dynamix.plugin.manager/Update.page
emhttp/plugins/dynamix/include/DefaultPageLayout.php
emhttp/plugins/dynamix/scripts/flash_backup
emhttp/plugins/dynamix/styles/default-azure.css
emhttp/plugins/dynamix/styles/default-black.css
emhttp/plugins/dynamix/styles/default-gray.css
emhttp/plugins/dynamix/styles/default-white.css

Revert "refactor: update os feedback"

---

emhttp/plugins/dynamix.my.servers/Registration.page
emhttp/plugins/dynamix.my.servers/data/server-state.php
emhttp/plugins/dynamix.my.servers/include/myservers1.php
emhttp/plugins/dynamix.my.servers/include/myservers2.php
emhttp/plugins/dynamix.my.servers/include/reboot-details.php
emhttp/plugins/dynamix.my.servers/include/state.php
emhttp/plugins/dynamix.my.servers/include/translations.php
emhttp/plugins/dynamix.plugin.manager/Downgrade.page
emhttp/plugins/dynamix.plugin.manager/Update.page
emhttp/plugins/dynamix/include/DefaultPageLayout.php
emhttp/plugins/dynamix/scripts/flash_backup
emhttp/plugins/dynamix/styles/default-azure.css
emhttp/plugins/dynamix/styles/default-black.css
emhttp/plugins/dynamix/styles/default-gray.css
emhttp/plugins/dynamix/styles/default-white.css

Revert "Revert "refactor: update os feedback""

---

emhttp/plugins/dynamix/Grub.page
emhttp/plugins/dynamix/Syslinux.page
etc/rc.d/rc.S

Update rc.S & Add GRUB config to WebGUI

---

emhttp/plugins/dynamix/include/Helpers.php
emhttp/plugins/dynamix/nchan/device_list

Required nvme_cli to be included in base packages.
Sample output.

NVME power state

---

etc/rc.d/rc.S

- Mistakes where made
- Fix boot for BTRFS and XFS

Fix regression error

---

emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
etc/rc.d/rc.docker
etc/rc.d/rc.libvirt

Prevents slowdown on Dashboard and Docker pages

Backport: reduce flash writes

---

emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix/include/Helpers.php

Fix SCSI controller update
Add Method to snapshots.

VM Manager updates and fixes

---

emhttp/plugins/dynamix/include/SmartInfo.php

Backport 1550 1551 1552

---

emhttp/plugins/dynamix/include/WOLrun.php

- Convert all MAC to lower
- Fix for syslog messages

Small bugfixes for unraidwold

---

emhttp/plugins/dynamix.docker.manager/include/DockerClient.php

Backport: Fix getDockerJSON

---

emhttp/plugins/dynamix/ManagementAccess.page

- backport #1648 (Fix IPv6 not displaying correctly on Management Access page if using default ports)

Backport Update ManagementAccess.page

---

emhttp/plugins/dynamix/include/UpdateDNS.php
emhttp/plugins/dynamix/include/Wrappers.php

Also backport my_logger() function to simplify backporting

Backport Disable UpdateDNS

---

emhttp/plugins/dynamix/ManagementAccess.page
emhttp/plugins/dynamix/include/ProvisionCert.php
etc/rc.d/rc.nginx

Backport: remove support for legacy unraid.net certs

---

emhttp/plugins/dynamix.docker.manager/scripts/dockerupdate
emhttp/plugins/dynamix.plugin.manager/include/UnraidCheck.php
emhttp/plugins/dynamix.plugin.manager/scripts/languagecheck
emhttp/plugins/dynamix.plugin.manager/scripts/plugincheck
emhttp/plugins/dynamix/scripts/statuscheck

and improve consistency in related files

Fix Docker notifications

---

emhttp/plugins/dynamix.docker.manager/scripts/dockerupdate
emhttp/plugins/dynamix.plugin.manager/include/UnraidCheck.php
emhttp/plugins/dynamix.plugin.manager/scripts/languagecheck
emhttp/plugins/dynamix.plugin.manager/scripts/plugincheck
emhttp/plugins/dynamix/scripts/statuscheck

Backport Fix Docker notifications

---

emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Fit XML window to page size

---

emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Rework of XML mobile page size.

Fix QEMU command line expanding if no data.

---

emhttp/plugins/dynamix/include/NotificationAgents.xml

新增企业微信消息通知，在国内还是这些用的较多。
The new enterprise wechat message notification is still more used in China.

Add Wxwork Notification Agent

---

emhttp/plugins/dynamix/include/.login.php

Backport: Fix Error 500 on login

---

emhttp/plugins/dynamix.vm.manager/VMUsageStats.page
emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/nchan/vm_usage
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/nchan/vm_dashusage

Fix VM memory size values on VM Usage
Fix issue with auto showing for QCOW2 files not in a VM path, should be manual
add evdev passthru

Various VM Manager Fixes

---

emhttp/plugins/dynamix/include/Wrappers.php

in http_get_contents, detect and recover from curl error 23

---

emhttp/plugins/dynamix/ShareList.page
emhttp/plugins/dynamix/include/DiskList.php
emhttp/plugins/dynamix/include/ShareList.php

Ignore parity disks, flash drive, and any disks marked as unmountable.

Fix detection of no mountable disks available.

---

emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Fix delete snapshot if the active one for VMs with spaces in name.
Error if clone of a VM with snapshots is attempted.

VM Updates

---

emhttp/plugins/dynamix.vm.manager/include/VMajax.php
emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix/include/Helpers.php

Update my_mkdir to include setting owner/group. Create parent dirs.

Update my_mkdir and VMs to use my_mkdir

---

emhttp/plugins/dynamix/ShareEdit.page

Changes:
- Fixes from extensive testing by Tom, Jorge, and Dan.
- Added indications when pools are configured but missing,
- Select missing pool in drop down and disable so user cannot choose a missing pool.
- Fix share floor based on secondary storage when pool->pool share is configured.

Fixes from extensive testing.

---

emhttp/plugins/dynamix.vm.manager/include/VMedit.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/include/Helpers.php

Fix templates broken by evdevs.
Fix for my_mkdir for names with spaces.
Fix for user templates, dont default to Windows default of i400fx if user tempate used.

VM Bug fixes.

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.vm.manager/VMSettings.page
emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
emhttp/plugins/dynamix.vm.manager/include/VMajax.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/javascript/vmmanager.js
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/include/DashboardApps.php
emhttp/plugins/dynamix/include/Helpers.php

Add a WebUI to VM template.
Parms to be converted at runtime.
[IP] - Guest agent must be install to support this variable. First IP used.
[VMNAME] - Spaces to be replaced with -
[PORT:XX] - XX is port number you want to use.

Create WebUI option in VM Template.

---

emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/javascript/vmmanager.js
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

Add nogpu option.

---

emhttp/plugins/dynamix/DeviceInfo.page
emhttp/plugins/dynamix/scripts/btrfs_check
emhttp/plugins/dynamix/scripts/xfs_check

- Add additional information to btrfs pools device info page.
- Change xfs repair on device info page to make it more user friendly.

Add more info to btrfs pools and more user friendly xfs repairs.

---

emhttp/plugins/dynamix/include/Helpers.php
emhttp/plugins/dynamix/include/update.parity.php
emhttp/plugins/dynamix/nchan/parity_list
emhttp/plugins/dynamix/scripts/monitor

- Parity check sometimes shows last historical check and not the parity check just completed.

Parity check not showing correct results.

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/javascript/vmmanager.js
emhttp/plugins/dynamix.vm.manager/nchan/vm_usage
emhttp/plugins/dynamix/nchan/vm_dashusage

Change VM URL menu item to open tab.
Some php fixes and code tidy.

PHP Fixes and opentab for VM URL

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/DisplaySettings.page
emhttp/plugins/dynamix/Settings.page
emhttp/plugins/dynamix/Tools.page

VM Manager
Remove subpools for drop downs.
GUI
Add option to disable favorites.

VM Remove subpools, Disable Favorites.

---

emhttp/plugins/dynamix/ShareEdit.page

- Fix translation of 'Apply' when performing 'POST' that blocks updating.
- Ssome code cleanup to combine messages and adjust some Java Script variable scope.

Fix share edit updates failing with languages other that English.

---

emhttp/plugins/dynamix/nchan/update_2

-  Dashboard doesn't show all of parity status with parity check/rebuild running.

Parity display on dashboard.

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/javascript/vmmanager.js
etc/rc.d/rc.apcupsd
etc/rc.d/rc.libvirt

apcupsd Change restart to run only if already running.
VM Fix for guest not init display when changing from DGPU to virtual.
VM Fix for clone with no disks
VM Add. support to block pull and commit for stopped vms
VM fix to rc.libvirt for multiple nics when bridge mode is changed.

Updates to rc.apcupsd and VM updates

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.docker.manager/include/Helpers.php
emhttp/plugins/dynamix/ArrayOperation.page
emhttp/plugins/dynamix/nchan/parity_list

- 'Done' button does not show on Array Operations page when parity operation completed.
- Add help text for PID Limit setting.

Parity check does not show completed on array operations page.

---

emhttp/plugins/dynamix/agents/PushBits.xml
emhttp/plugins/dynamix/agents/Pushbullet.xml

- Fix for PushBits and Pushbullet not showing in the WebUI

Fix for notification agents

---

emhttp/plugins/dynamix/scripts/ssd_trim

Backport: Make trim consistent between "trim now" and cron job

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
etc/rc.d/rc.libvirt

VM Fix for guest not init display when changing from DGPU to virtual.
VM fix to rc.libvirt for multiple nics when bridge mode is changed.

Backport fixes

---

emhttp/plugins/dynamix/DashStats.page

Backport: Fix tile management showing a blank dialog

---

emhttp/plugins/dynamix.vm.manager/include/VMedit.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
etc/rc.d/rc.local

FIX VM Template formating issue of other pci

Move restore favorites after plugin installs + VM Template formatting for PCI others

---

etc/rc.d/rc.docker

- Add `IPV6_FORWARD` to rc.docker and set it to `ACCEPT` instead of `DROP`

Add IPv6 forward rule

---

emhttp/plugins/dynamix/WG0.page
emhttp/plugins/dynamix/WGX.page
emhttp/plugins/dynamix/nchan/device_list

- Also did some minor gui fixes.

Fix php warning in device_list; VPN Manager not showing tunnel status.

---

emhttp/plugins/dynamix.vm.manager/VMUsageStats.page
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/nchan/vm_usage
emhttp/plugins/dynamix/nchan/vm_dashusage

Three columns inuse/Current/Maximum

Fix memory Stats in VM Usage.

---

emhttp/plugins/dynamix.apcupsd/UPSdetails.page

Backport Fix UPS settings page when config contains empty values

---

emhttp/plugins/dynamix.vm.manager/VMSettings.page
emhttp/plugins/dynamix/include/.login.php
emhttp/plugins/dynamix/include/DefaultPageLayout.php
emhttp/plugins/dynamix/scripts/system_information

Backport: Use "go links" when linking to Docs

---

emhttp/plugins/dynamix.vm.manager/VMMachines.page
emhttp/plugins/dynamix.vm.manager/include/VMajax.php
emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php

This will check VM name does not include characters that are not valid for ZFS. Existing VMs are not modified but will throw error and disable update if invalid characters are found.

Add ZFS Checking

---

emhttp/plugins/dynamix/include/.login.php
emhttp/plugins/dynamix/include/.set-password.php

Backport: fix: replace document write usages

---

emhttp/languages/en_US/helptext.txt

Backport: Fix typo in help text

---

emhttp/plugins/dynamix.vm.manager/include/libvirt.php
emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
emhttp/plugins/dynamix/DashStats.page

Fix vmusage stopping when you on a new page on a tab
Unmap Default and Multifuncton
Set default for new VMs to discard="unmap"
Fix BSOD for VMs and Multifunction.

Fix vmusage stopping/Unmap Defaults and Fix Multifunction.

---

emhttp/plugins/dynamix/include/CPUset.php
emhttp/plugins/dynamix/include/UpdateTwo.php
emhttp/plugins/dynamix/scripts/diagnostics

This is the last change to make the GRUB bootloader fully compatible with the unRAID WebUI

GRUB compatibility changes

---

emhttp/plugins/dynamix/DeviceInfo.page

Add a warning mnessage to the pool rename dialog warning about share storage will be affected.

Add warning message to rename pool dialog.

---

emhttp/plugins/dynamix/ShareEdit.page
emhttp/plugins/dynamix/ShareList.page
emhttp/plugins/dynamix/include/ShareList.php

Fix share list not showing invalid storage configurations and some code cleanup.

Fix share list.

---

emhttp/plugins/dynamix/Apps.page

Adjust URL for CA installation

---

emhttp/languages/en_US/helptext.txt

https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/Manpage/btrfs-balance.html
to 
https://man7.org/linux/man-pages/man8/btrfs-balance.8.html
-- Rysz

en_US/helptext.txt: Fix broken link in GUI

---

emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
emhttp/plugins/dynamix.docker.manager/include/Helpers.php

This PR allows users to assign different Container networks to a Docker container without using `--net=container:<CONTAINERNAME>` in the Extra Parameters.
The PR is completely backwards compatible and will not harm templates which already have `--net=container:<CONTAINERNAME>` in them.

Allow users to select Container networks in the WebUI

---

emhttp/plugins/dynamix.vm.manager/nchan/vm_usage
emhttp/plugins/dynamix/nchan/vm_dashusage

Fix issue with net and disk values being to large.

Fix VM usage stats value if timer > 1 sec.

---

emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php

- Fix orange text "not available" to use the default text colour for 3rd party containers

Fix for 3rd party containers "not available" colour

---

etc/rc.d/rc.sshd

- Remove trailing slash to be sure to grab the correct PIDs

Fix for rc.sshd

---

emhttp/plugins/dynamix/ShareEdit.page

Delete share is always visible and enabled only when it is safe to delete the share.  Show tool tip on 'Delete' and checkbox  indicating when a share can and cannot be deleted.

Delete share is always visible.

---

emhttp/plugins/dynamix/nchan/device_list

Was preventing the main page from populating with data in some cases

Fix PHP error in device_list

---

emhttp/plugins/dynamix.docker.manager/scripts/dockerupdate
emhttp/plugins/dynamix.plugin.manager/Plugins.page
emhttp/plugins/dynamix/DashStats.page
emhttp/plugins/dynamix/Eth0.page
emhttp/plugins/dynamix/include/FileSystemStatus.php
emhttp/plugins/dynamix/include/Helpers.php
emhttp/plugins/dynamix/include/OpenTerminal.php
emhttp/plugins/dynamix/include/StartCommand.php
emhttp/plugins/dynamix/scripts/reiserfs_check
etc/rc.d/rc.K
etc/rc.d/rc.acpid
etc/rc.d/rc.bind
etc/rc.d/rc.dnsmasq
etc/rc.d/rc.elogind
etc/rc.d/rc.inetd
etc/rc.d/rc.mcelog
etc/rc.d/rc.messagebus
etc/rc.d/rc.nfsd
etc/rc.d/rc.ntpd
etc/rc.d/rc.rpc
etc/rc.d/rc.samba
etc/rc.d/rc.smartd
etc/rc.d/rc.sshd
etc/rc.d/rc.udev
etc/rc.d/rc.wsdd2
sbin/mover

killall and pgrep updates.

---

emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
emhttp/plugins/dynamix.vm.manager/include/VMajax.php
emhttp/plugins/dynamix/include/DashboardApps.php

Force scaling local.

---

emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
emhttp/plugins/dynamix.docker.manager/include/Helpers.php
share/docker/tailscale_container_hook

- Fix php warning when updating containers
- Make sure that https is enabled

Fixes & improvements

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
emhttp/plugins/dynamix.docker.manager/include/Helpers.php
share/docker/tailscale_container_hook

Added drop down for TS Routes, this seems like a well used option.

Docker add Routes drop down

---

emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php

- Move Tailscale information from `Version` to `Network` column

Move TS icon to Network

---

emhttp/plugins/dynamix.docker.manager/javascript/docker.js
emhttp/plugins/dynamix/include/DefaultPageLayout.php

Warning for clicking an external link

---

emhttp/plugins/dynamix.docker.manager/DockerContainers.page
emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
emhttp/plugins/dynamix.docker.manager/styles/style-azure.css
emhttp/plugins/dynamix.docker.manager/styles/style-black.css
emhttp/plugins/dynamix.docker.manager/styles/style-gray.css
emhttp/plugins/dynamix.docker.manager/styles/style-white.css
share/docker/tailscale_container_hook

- Make TS icon size relative to text size for automatic scaling with font changes (from #1912 )
- Use `tooltipster` to show information about TS on Docker page
- Change `Version` to `Tailscale`
- Add CSS elements to themes for tooltip dividers

Use `tooltipster` for TS information on Docker page

---

emhttp/plugins/dynamix/include/ShareList.php

Backport code from 7.0.0 that shows an indicator on a share when a storage location is invalid, such as a pool has been renamed and the share has not been reconfigured for the new pool name.

Backport: indicator when share pool is invalid.

---

emhttp/languages/en_US/helptext.txt

backport of #1856 (as requested by @ljm42 )

(backport) en_US/helptext.txt: Fix broken link

---

emhttp/plugins/dynamix/scripts/feedback

I used the version from 7.0 to update the 6.12 script as it has been rewritten and is a lot cleaner code.  This form is stand alone and no other modules should need to be changed.  A quick test worked properly.

Backport: require email in feedback form

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
share/docker/tailscale_container_hook

- Re-trigger check for available TS options on container network change

Run container network check if network is changed in Docker

---

emhttp/plugins/dynamix.docker.manager/DockerSettings.page
emhttp/plugins/dynamix/OutgoingProxy.page

These drop downs are not displaying correctly and cannot be selected.

Fix drop downs not working.

---

emhttp/plugins/dynamix/DashStats.page
emhttp/plugins/dynamix/DateTime.page
emhttp/plugins/dynamix/include/DashboardApps.php
emhttp/plugins/dynamix/sheets/DateTime.css
etc/rc.d/rc.ntpd

- Add new parameter "NTP interval", this can be useful when you run your own NTP servers
- Add pool support, this allows a round-robin selection of NTP servers out of a pool, and improves server availability

NTP enhancements

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix/SecurityNFS.page

Add help to clarify how to use the NFS Rules text area.

Add Share NFS security Rules help.

---

emhttp/plugins/dynamix/OutgoingProxy.page
emhttp/plugins/dynamix/include/OutgoingProxy.php
emhttp/plugins/dynamix/include/OutgoingProxyLib.php
emhttp/plugins/dynamix/scripts/outgoingproxy

- Change password fields to type='password'.
- Store passwords in config file so special characters are preserved.
- This allows special characters to be used in passwords.

Enhancements to password handling in Outgoing Proxy Manager.

---

emhttp/plugins/dynamix/ShareEdit.page
emhttp/plugins/dynamix/include/ShareList.php

The changes last submitted in a PR dis not stick.  This PR should get it up to date.

Last set of changes did not stick in share edit.

---

emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
emhttp/plugins/dynamix.docker.manager/include/Helpers.php

- Make Tailscale State Directory in XML persistent even when Tailscale is not enabled
- Fix minor visual bug

Imporvements to Tailscale

---

emhttp/plugins/dynamix/scripts/diagnostics

- add aspm status to `diagnostics`

Add aspm status to `diagnostics`

---

emhttp/languages/en_US/helptext.txt
emhttp/plugins/dynamix/ShareSettings.page

Add a setting for the number of fuse file descriptors in Global Share Settings.

Setting for the number of fuse file descriptors.

---

emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
emhttp/plugins/dynamix.docker.manager/include/Helpers.php
share/docker/tailscale_container_hook

- Add Translation layer for Official Tailscale Sidecar container
- Switch to `version_compare` to check Tailscale version
- Split Docker Post Arguemnts on first `;`
- Fix broken pattern for Advertise Routes

Various TS improvements

---

share/docker/tailscale_container_hook

backport: Change TS Sidecar routine

---

emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php

- make sure to only pull update information for Docker containers managed by `dockerman`
- make sure to only display update information on Docker page for containers managed by `dockerman`

Backport: Update status Docker containers

---

emhttp/plugins/dynamix.docker.manager/scripts/docker_init

Backport Last container wouldn't autostart

---

emhttp/plugins/dynamix/scripts/diagnostics

Backport: fix: diagnostics: anonymize IPv6 addresses in lsof.txt

---

emhttp/plugins/dynamix/nchan/file_manager

backport: File manager: fix file overwrite on move operation
