- plugins/dynamix.plugin.manager/scripts/plugin
plugincheck script doesn't check if a plugin is still installed.  Only if the .plg still exists in /tmp/plugins.  Update notices will happen until a reboot is issued
> Remove the old temp .plg file on remove

- plugins/dynamix/MoverSettings.page
- plugins/dynamix/ParityCheck.page
Show a warning message instead when selection is unavailable
> Make Parity Check and Mover Settings unconditional

- plugins/dynamix/include/update.parity.php
If parity check schedule is set to 1st week, 2nd week, etc a cron error is logged when when not on the selected week due to return value of 1 from the date check.  Return a value of zero instead.
> Prevent cron error entering syslog.

- plugins/dynamix/include/SystemInformation.php
It would be great to start integrating ECC/EDAC support in unRAID, one of the first steps might be to display relevant information from the BIOS/UEFI.
Reducing the `dmidecode -t 16` calls to one is preferable, I am not aware if `Maximum Capacity` and `Error Correction Type` can be extracted with `awk` in one go without having to `explode` the row as done with `$cache`, otherwise it would be fine.
[
](url)
> Addition of Error Correction Type information

- plugins/dynamix.docker.manager/Docker.page
Occasionally, the array is started but the docker service fails to start (unmountable docker.img as an example)  
Toss up a message instead of simply displaying a blank page
> Display message if docker service fails to start

- plugins/dynamix/scripts/diagnostics
ps -auxef includes the environment variables for running containers, which may contain sensitive information.
Change to ps -auxf which does not
> Partial Reversion of #221

- plugins/dynamix.docker.manager/include/DockerClient.php
https://forums.lime-technology.com/topic/57985-docker-failure-to-remove-orphan-image-due-to-similar-named-image/
Also handles rare edge case of multiple containers installed with different tags all referring to an identical image at the time of upgrade
> Fix docker updates occasionally trying to remove wrong image

- plugins/dynamix.docker.manager/include/CreateDocker.php
Current behaviour is that the Apply button does not enable when changing the path via the file browser.  Only by manually typing in a path
> Enable Apply button when changing a container's host path

- plugins/dynamix.docker.manager/DockerContainers.page
- plugins/dynamix.docker.manager/include/CreateDocker.php
- plugins/dynamix.docker.manager/include/DockerClient.php
- plugins/dynamix.docker.manager/javascript/docker.js
- plugins/dynamix/DashboardApps.page
Every container installed via CA should already have the Support Link present (if installed post 6.2)
Majority of apps in CA also have a project link present (and passed to dockerMan), but thus far dockerMan hasn't saved that entry on user templates, so the Project link on the context menus will only appear for new containers added after the PR is approved.  (After published, I'll probably post a script to update everyone's user-templates with the appropriate Project URL's)
Additionally, dockerMan template authoring mode will also now support the most common CA xml entries (but nowhere near all) that template authors currently have to add manually to the generated xml file
> Add in Support & Project Links to Docker Context Menus

- plugins/dynamix.docker.manager/DockerSettings.page
Two additions are added to better support custom networks:
1. GUI allows any interface without IP address to be used for Docker. This gives the user more possibilities
2. Automatic generated interfaces and be included or excluded. This can help with potential conflicts.
A update for rc.docker is needed too, this will be sent by email.
> Enhancements for docker custom networks

- plugins/dynamix/scripts/diagnostics
Don't anonymize system share names (such as appdata,domains,isos,system), this will make it easier to find the right file when troubleshooting system shares.
> enhancement to diagnostics

- plugins/dynamix.plugin.manager/scripts/plugin
Currently, to use the plugin manager as an easy method of running one-off scripts that DO NOT need to be re-run at boot time, the script needs to exit with a non-zero return code to force pluginMan to not copy the .plg to /boot/config/plugins.  Ideally, the script should exit with a zero return code for successful execution.
The trigger for this is a new <PLUGIN> attribute of "noInstall" When its value is non-null, the .plg will not get saved to /boot/config/plugins, but the .plg can still exit with a proper zero return code.
Admittedly, not too much call for this, but it would have come in handy for my Support / Project template update script for 6.4.1-rc2
> Add ability for pluginMan to not install the .plg file

- plugins/dynamix/DashboardApps.page
Ain't nobody got time for that
> Update app icons container slidedown speed

- plugins/dynamix.docker.manager/include/CreateDocker.php
Recursively remove any <script> or <iframe> from all elements in a template prior to displaying.
> Docker Security: Remove <script> and <iframe>

- plugins/dynamix.docker.manager/include/DockerClient.php
webUI being automatically updated by dockerMan on updates results in people that have as an example reverse proxied their containers and needing to have a different webUI always having to redo their changes.
> Docker: Don't automatically update webUI entry on templates

- plugins/dynamix.docker.manager/include/DockerClient.php
Solves the problem with dockerMan pumping out tons of simpleXML errors when a Mac creates its ._ files
See https://lime-technology.com/forums/topic/70636-beta-diskspeed-hard-drive-benchmarking-unraid-6/?page=5&tab=comments#comment-653133  (Hasn't really appeared prior because this template was originally published as a .xml the user had to copy manually onto the flash drive)
> Docker skip hidden files when listing directories

- plugins/dynamix.docker.manager/include/CreateDocker.php
Docker object labels:
https://docs.docker.com/config/labels-custom-metadata/
More and more containers are taking advantage of container metadata
where environment variables are not necessary.
Traefik is a good example:
https://docs.traefik.io/configuration/backends/docker/#on-containers
> Add support for Docker Labels to Docker plugin

- plugins/dynamix.docker.manager/include/DockerClient.php
HTML tags are converted to HTML entities somewhere along the chain and `CreateDocker.php` generates:
`addLog('<b>Error: Image can not be deleted&lt;br&gt;&lt;i&gt;In use by other container(s)&lt;/i&gt;</b>');`
> Strip HTML from back-end

- plugins/dynamix.docker.manager/include/DockerClient.php
Dockerman is generating incorrect icon names for certain image tags
examples:
openhab/openhab:2.3.0-amd64-debian -> --icon.png
binhex/emby:1.4.0 -> --icon.png
Seems the regex for extracting the icon name from the image tag is insufficient.
> Correct docker container icon name generation

- plugins/dynamix.plugin.manager/include/ShowPlugins.php
Supports a new attribute on plugins (**support**) which will contain a link to the appropriate support thread in the forum. 
Easiest way to test is to remove then reinstall CA which now has that attribute present.
If this PR does get added to dynamix, then at time of release I would publish a script to update all the .plg's present on a user's system with the appropriate attribute, and also have CA on installation of a .plg automatically add it to the .plg if it doesn't already exist (since I insist that CA's XML file has a support entry)
Only dmacias would have to adjust his README.md files as he is the only one who includes a link to support already contained within it.
> Plugin List: Show support thread if attribute exists

- plugins/dynamix.plugin.manager/scripts/plugin
An oversight from #347 
CA (or the script to be published at time of 6.6 release) adds in automatically a support link to plugins.  But, the support link would not survive an update to the plugin.
If CA has already added in a support link, then rewrite it to the new plugin at time of update.
> Plugins: Preserve support link when updating plugin

- plugins/dynamix.docker.manager/include/CreateDocker.php
Because under FAT32, my-plexmediaserver == my-PlexMediaServer.  Solves an edge case
> dockerMan: Avoid filename collisions on FAT32

- plugins/dynamix/scripts/diagnostics
IE: loads.txt is not being generated correctly on 6.6-rc1
> Allow inline execution of exert without having to specify variable

- plugins/dynamix.docker.manager/include/Helpers.php
While I think this was a decent idea, in actual practice there are too many possibilities / permutations of quoting etc that can potentially result in a false positive and prevent the user from executing their container (has already happened twice).  Net result is that the security routine would have to be continually updated as more legit usages come to light.
Since the whole point of the original change was to prevent repository maintainers from maliciously executing arbitrary commands in the docker run and not to impact end-users at all, this will have to be purely enforced on CA's end instead where the permutations are far less because of only having to deal with a raw template
> Revert docker run Security

- plugins/dynamix/CPUvms.page
Should make possible to (re)allocate CPU resources across all containers faster. Currently, it requires manual clicking on thread numbers per container individually, which in a large pool of containers can be very repetitive. The change allows for thread numbers to be clickable, doing so enables or disables thread pinning across all containers.
> Add global CPU core pinning for containers

- plugins/dynamix.docker.manager/include/GetContainerSize.php
The docker logs command outputs to both stdout and stderr depending upon the type of log entry.  Both have to be accounting for in determining the log size
> I (shamelessly) took the part from Squid's script to include log file sizes.
Looks like you missed that bit in my code bonienl  :)
> Fix container log size

- plugins/dynamix.docker.manager/include/CreateDocker.php
CA currently when installing multiple previously installed apps will copy, modify, and execute a different version of CreateDocker.php to avoid a harmless display error.  Minor code adjustment to prevent CA from having to do that (since it may at some point in the future break).
> Code change to prevent CA from modifying system file

- plugins/dynamix.docker.manager/include/DockerClient.php
- plugins/dynamix.docker.manager/include/Helpers.php
This is a rewrite to allow better support for private docker registries (in my case, free gitlab.com).
This rewrite is not tested on an unraid install, since I'm not sure how to set that up (see #400).
The code itself is tested in so far, as I ran it outside of unraid to get the api flow correctly and to make sure the `/root/.docker/config.json` is parsed correctly.
Following things could be problematic:
- Needs read access to `/root/.docker/config.json`
- Anybody wishing to use this would need to make sure `/root/.docker/config.json` is persistent across reboots
Otherwise it would basically be following a normal usage of private docker registries, for example Gitlab:
- Create gitlab account and repo, push docker image to docker repository
- Login to private docker repo via `docker login …
> Improve private docker registry support (correctly pulling and updating containers)

- plugins/dynamix/scripts/diagnostics
To help with the usual questions of why are all my drives spinning up etc.  Also helps with diagnosis with mover logging being disabled by default.
> Diagnostics Add share storage location

- plugins/dynamix.docker.manager/include/CreateDocker.php
#363 has been implicated in a glitch in the docker template system.  While I cannot replicate the issue at all, revert the PR as the edge case issue that it solved has only ever occurred during synthetic tests.  IE: revert the code and see if the reported "issues" still occur.
> Revert FAT32 filename collisions

- plugins/dynamix.plugin.manager/include/PluginHelpers.php
Under certain circumstances, a valid plugin without a determinable icon will return
Warning: preg_split(): Compilation failed: range out of order in character class at offset 5 in /usr/local/emhttp/plugins/dynamix.plugin.manager/include/PluginHelpers.php on line 52
Suppress it
> Suppress PHP error under certain circumstances if plugin does not have an icon

- plugins/dynamix/include/update.parity.php
Basically a revision of a commit in #380.  Obviously can't test all of the various combinations.  But it should work as there were no complaints before, and it doesn't work now (https://forums.unraid.net/bug-reports/stable-releases/scheduled-parity-check-did-not-run-r339/)
Would appreciate someone else checking also.
> Fix custom parity check schedule

- plugins/dynamix.plugin.manager/scripts/plugin
Fatal typo in my original PR #473 that prevents any plugin ( or a subsequent OS update ) from installing.  My bad -> happened because I was too lazy to merge into my fork the tested code and simply manually did a patch.
> Fix plugin download routine

- plugins/dynamix.docker.manager/include/DockerContainers.php
- plugins/dynamix.docker.manager/javascript/docker.js
- plugins/dynamix/include/DashboardApps.php
Because more and more maintainers don't include in the support thread enough info to configure the container, but rather include on the registry page
> Docker: Add More Info link (docker registry) to context menus

- plugins/dynamix.plugin.manager/scripts/plugin
Should solve the odd problem with CA where updates effectively remove the plugin, due to user clicking the CA link to update itself, but auto update (eg) has already updated the plugin (ie: auto update updated it while the CA page was open)
> Don't allow plugin updates to same version

- plugins/dynamix/scripts/notify
This allows for a little more flexibility if users or plugins want to tie into the systems notification system. If there are one off notifications or notifications that only one person would be interested in, a script can pass in -r "myemail@email.com" and the notify system will ignore the recipients in the notification settings, instead sending to the provided email argument.
See this [post](https://forums.unraid.net/topic/81268-modified-notify-system/) for more information on the reason behind the modification.
Also important to note that these changes do not affect default functionality at all and require no updates to anything using the notification system currently.
> Modified notify script to allow overriding email recipients in notification settings

- plugins/dynamix/include/DefaultPageLayout.php
- plugins/dynamix/styles/default-azure.css
- plugins/dynamix/styles/default-black.css
- plugins/dynamix/styles/default-gray.css
- plugins/dynamix/styles/default-white.css
A number of advantages
- From my point of view, the most important is that it opens up the banner warning to 3rd party plugins, without CA's function having to create its banners with a z-index greater than the OS update z-index
- Allows multiple banner warnings ( browser will cycle through them ) (Previously, System Notifications Disabled couldn't be displayed if an OS or Reboot Warning was present ) (If desired, ACS Override can now via suitable programming toss up a reboot now banner instead of only appearing on its own page)
- If user dismisses an OS update, if another becomes available, then the banner will re-appear unlike previous operation if the browser window was not closed.
- Any given warning is able to be dismissed without any programming
- Warnings are able to be removed by …
> Revamp Banner Warning System

- plugins/dynamix/include/NotificationAgents.xml
A discussion in the unRAID Telegram group has revealed that adding the notifications receiving Telegram bot to a group chat does not work as group chat IDs start with a negative sign and the current regex does not account for that, this PR should fix it.
There's also the suggestion from a user that we expose the chat ID as a text field to the notification agent settings, although I am having the concern that this might confuse users that are not that familiar with the Telegram API and am leaning towards the automatic chat ID fetching. Thoughts?
> enable group chat IDs, update helper description

- plugins/dynamix/scripts/diagnostics
Since most people think that memory is memory and never check QVLs, assume you can mix types no problems, etc.
> Diagnostics: include info on physical memory sticks

- plugins/dynamix/ShareEdit.page
Try and make the Use cache option for a User Share less likely to be misinterpreted by new Unraid users
> Improve Use Cache option

- auth_request.php
- login.php
- plugins/dynamix/include/local_prepend.php
Also, enable session.use_strict_mode to prevent session fixation attacks
> Only create session when user successfully logs in

- plugins/dynamix.docker.manager/DockerRepositories.page
We all know my preference is to completely delete this file (that was shot down a while ago), but it would solve (or at least help) with the odd user getting confused over what it actually does by naming the tab correctly
> Rename docker repositories tab to template repositories

- plugins/dynamix/DashStats.page
- plugins/dynamix/Processes.page
https://forums.unraid.net/bug-reports/stable-releases/672-memory-and-motherboard-cogs-on-dashboard-direct-to-non-applicable-target-pages-r715/
Up to @bergware
> Change dashboard link for mb/mem

- plugins/dynamix/scripts/diagnostics
Original code wasn't working.  It was attempting to open the literal file ..../*.xml instead of applying the wildcard
> Diagnostics: Remove OSK info from VM xml

- plugins/dynamix/Diagnostics.page
The filename generated by the webGUI's diagnostics wouldn't take into account the user's time zone.  (Time would always be UTC/GMT)
Set the filename according to the date / time on the browser
> Diagnostics: Adjust for timezone from webGUI

- logging.htm
- login.php
- plugins/dynamix.docker.manager/include/ContainerSize.php
- plugins/dynamix.docker.manager/log.htm
- plugins/dynamix.plugin.manager/include/ShowChanges.php
- plugins/dynamix/include/Boot.php
- plugins/dynamix/include/CryptoBenchmark.php
- plugins/dynamix/include/DefaultPageLayout.php
- plugins/dynamix/include/Feedback.php
- plugins/dynamix/include/ParityHistory.php
- plugins/dynamix/include/ReplaceKey.php
- plugins/dynamix/include/SelectCase.php
- plugins/dynamix/include/SystemInformation.php
- plugins/dynamix/include/TrialRequest.php
- update.htm
This adds `<meta name="referrer" content="same-origin">` to all pages, which will prevent browsers from sending referrer information when linking offsite.  See:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
> Block referrals to 3rd Party Sites

- plugins/dynamix.docker.manager/include/CreateDocker.php
\n not being preserved between advanced view and basic view of overviews, making for some strange looking overviews in basic.
> dockerMan: Preserve \n on overview in basic mode

- plugins/dynamix/scripts/notify
Will be utilized by CA to send a notification, but not have the notification appear on the browser but rather as a banner warning
> Notifications: Add switch to not send a browser notification

- plugins/dynamix.docker.manager/include/CreateDocker.php
- plugins/dynamix.docker.manager/include/DockerClient.php
- plugins/dynamix/ArrayOperation.page
It's the one place in the docker UI where changing an element on one of the duplicated containers will not take effect or affects both of them -> depending upon the alphabetical order of the containers.
Multiple instances of containers are far more prevalent now than when dockerMan was first introduced, and the original method of tagging to reflect different apps installed is no longer sufficient.
Minor downside is that a re-download of all the icons will happen when _first_ hitting either dashboard or docker pages to reflect the new naming scheme.
> Allow duplicate containers different icons

- plugins/dynamix/include/DefaultPageLayout.php
My bad.  It originally worked prior to the revamp required by the reboot notifications being persistent.
> Fix Banner Warnings Not Dismissing without reload of page

- plugins/dynamix.docker.manager/javascript/docker.js
This pull request uses the docker update dialog also for the update entry in the context menu. This makes sure that users do not accidentally update their containers.
Reference: https://forums.unraid.net/bug-reports/stable-releases/docker-image-update-dialog-missing-cosmetic-issue-r941/
> Use update image dialog for update entry in docker context menu

- plugins/dynamix/include/DefaultPageLayout.php
Gives the ability to provide a Display_Name for when displaying task menu bar as having spaces in the file name seems to mess things up further.
> Task Plugins: Providing Ability to define Display_Name

- plugins/dynamix/ManagementAccess.page
@bergware You might want to do a search on every swal call.  With multi-language, any time & apos ; shows up in a swal dialog it shows up literally without html:true being set.  This instance was obvious, since it appeared in English.
> Fix &apos; appearing when provisioning

- plugins/dynamix/include/DefaultPageLayout.php
If the request to Notify.php was redirected to the login page, redirect the current tab there as well.
> Detect invalid session and logout current tab

- plugins/dynamix.docker.manager/include/DockerClient.php
This fixes the "Check for updates" button not working for images from private docker registries that don't use Bearer tokens for authentication. I tested this using the DockerRegistry container from Community Applications and Traefik providing the basic auth.
> Added support for private docker registries with basic auth or no auth, and improvements for token based authentication

- plugins/dynamix/DashStats.page
This prevents the page from polling for 'update.wireguard.php' when the WireGuard plugin is installed but there are no tunnels defined
> Remove WG from Dashboard if no tunnels defined

- plugins/dynamix.docker.manager/include/CreateDocker.php
2 characters minimum, must start with a-zA-Z0-9 2nd+ characters a-zA-z0-0.-_
> dockerMan: Only allow name compatible with docker

- plugins/dynamix/include/Helpers.php
Slightly tweaks the `autov()` helper function to prevent the failing with a syntax error when the file doesn't exist. When the function fails it will now append a fallback of `autov_fileDoesntExist` as the query string to signify `autov()` failure.
This should help with certain troubleshooting situations.
> improve: helper autov(), fail syntax error prevent

- plugins/dynamix.docker.manager/DockerContainers.page
- plugins/dynamix.docker.manager/include/DockerContainers.php
- plugins/dynamix/DashStats.page
Since Santa got me an (ugh) iPad figured I'd fix https://forums.unraid.net/topic/84824-docker-tab-not-scrolling-on-ipad/?tab=comments#comment-931502
The big difference is that on the dashboard you can only drag to rearrange from each section's title bar, and on the docker tab only from the new up/down arrow on the right.  This fixes the not able to scroll on iPad devices either of the pages.  
You still can't rearrange either of the displays from either Android or iOS, but no one is complaining about that (and you couldn't do it previously either)
> Fix: Dashboard / Docker scrolling on iPad devices

- plugins/dynamix/include/local_prepend.php
Sends "samesite=strict" when HTTPS is enabled and "samesite=lax" when it is not.  HTTPS users will have samesite protection and be able to switch between servers if they have the same domain name, while HTTP users will not have samesite protection but will still be able to switch between servers
> fix: login prompt when switching between servers

- plugins/dynamix/Diagnostics.page
- plugins/dynamix/include/Download.php
- plugins/dynamix/scripts/diagnostics
Switches diagnostics to run via a Web Socket
- Will eliminate the fairly common timeouts prevalent, especially with wide arrays and drives spun down
- If a command crashes, it's helpful to the forum to know exactly where it hung up
- Even if the web socket isn't working (browser issues), the file is now also saved to the flash drive.
- Safeguards in place to handle if the user runs multiple diagnostics at the same time.
> Switch Diagnostics to web socket

- plugins/dynamix/scripts/diagnostics
Easier to view go script without having to extract it first
> Diagnostics: include go as go.txt

- plugins/dynamix/include/PageBuilder.php
If the format of the .page is completely wrong, then every page gets corrupted, and the system becomes unusable.  Personally, I hate it that every .page file can potentially take down the entire GUI in case of an error.  Blocking the output of the parse_ini_file protects the GUI, and the file gets logged to inform the user / forum.
Realistically, a released plugin should never trigger this code, but it's really annoying when it does (https://forums.unraid.net/bug-reports/stable-releases/gui-partially-didnt-working-r1327/) as it's not obvious anywhere what plugin is causing it.
> Protect GUI from invalid .page files

- plugins/dynamix/DeviceInfo.page
https://forums.unraid.net/bug-reports/stable-releases/691-unable-to-delete-new-pool-emhttpd-error-changeslots-missing-csrf_token-r1361/
> Fix missing CSRF when deleting pool

- plugins/dynamix.docker.manager/include/CreateDocker.php
- plugins/dynamix.vm.manager/templates/Custom.form.php
Chrome / Firefox have very strange results when autofilling on containers:  Fixed IP will get "root" and the first password entry will have the root password.
Editing VMs have a share filled out of "root" and the VNC password of root password.
> Prevent autofilling of passwords on containers/vms

- plugins/dynamix/include/CPUset.php
Pinning via CPU pinning settings does not work if there is not a template present  (ie: the user installed manually via command prompt)
https://forums.unraid.net/topic/88796-i-cannot-save-the-settings-of-cpu-pinning-docker/?tab=comments#comment-957388
> Docker: Don't allow CPU pinning if no template present

- plugins/dynamix/NotificationAgents.page
- plugins/dynamix/include/NotificationAgents.xml
- plugins/dynamix/include/SMTPtest.php
- plugins/dynamix/scripts/notify
Users with the Discord agent currently installed will need to go to the Notification Agents page, make a small change to the Discord agent, and hit Apply to regenerate the script.
Note: When clicking links from web-based email clients you will likely be redirected to the login screen due to SameSite cookie restrictions. Links can be copy/pasted to the address bar instead.
> Include links in email and Discord agent notifications

- plugins/dynamix.docker.manager/include/CreateDocker.php
Reverts limetech/webgui#782
Fatal flaw in the logic.  If an already installed container fails to start due to an error in the docker run command (eg: port already in use, nvidia problems etc), it's impossible to see the docker run command.  Need to rethink
> Revert "dockerMan: Selectable start upon install"

- plugins/dynamix/include/NotificationAgents.xml
- plugins/dynamix/scripts/notify
6.10 removes /var/run/nginx.origin, need to build links to http://tower.local
Redirects will forward user to a better url if one is available.
> Notification links will point to http://tower.local

- plugins/dynamix/include/DefaultPageLayout.php
Up to @bergware.  As an example, I had no idea that UD injected code into every page of the UI.
> When viewing source, identify which .page file is responsible

- plugins/dynamix.docker.manager/include/Helpers.php
This drops compatibility with newly created templates being installed on 6.0 / 6.1  It does not drop compatibility with installing templates created on 6.0 / 6.1 when on 6.2+
Basically it just removes the redundant entries in the xml
> Docker: Only save templates as v2

- plugins/dynamix/Syslinux.page
While this case isn't explicitly covered by the banner warning (no syslinux.cfg file), if this file is missing / corrupted then the system probably won't boot if the flash drive is still present.   I told JonP as I run across PHP errors in the WebUI I'd put in code to silence them or handle them as applicable.
> Silence PHP error on syslinux page if flash drive is missing

- plugins/dynamix/include/UpdateDNS.php
Bring the base UpdateDNS script more inline with the plugin's UpdateDNS, where it sends data under two conditions:
* either the system is signed in, in which case also send the 'servercomment' variable
* or SSL is enabled, in which case also send the 'internalip' variable
If both conditions are met, then both variables should be sent.
> UpdateDNS servercomment and internalip tweaks

- plugins/dynamix.docker.manager/include/CreateDocker.php
Reverts https://github.com/limetech/webgui/pull/792 in order to support the CA pitch  (And should be reverted anyways for future capabilities)
> Re-add hidden donation links to docker templates

- plugins/dynamix/include/UpdateDNS.php
Modify the stock UpdateDNS script so that when the system is signed it, it will send $internalprotocol, $internalport, $internalhostname so that the My Servers Dashboard can display the Local Access URL.
The plugin's UpdateDNS already sends this information
> feat: updatedns - send proto, port, and hostname

- plugins/dynamix.docker.manager/include/DockerClient.php
CA requires getAllInfo to operate properly with a new update, but in case of networking issues this slows down the system if dockerMan is unable to download the icon (and keeps trying).  CA doesn't care about the icon, so skip downloading them if the request is coming from CA
> Allow CA to get all docker info without having to download icons if not present

- plugins/dynamix.docker.manager/include/DockerClient.php
I often specify custom WebUI URLs based on my network/local-domain
setup. I rarely if ever use "http://[IP]:[PORT:8888]/" templated URLs.
This change maintains support for the existing templated
bridged/host-network URL schema while enabling the "WebUI" affordance
for containers where the user explicitly entered a WebUI url, e.g.
"https://grafana.mylan.io"
> Always show "WebUI" for user specified URLs

- plugins/dynamix/nchan/update_2
Please find suggested changes to Dash board view if Parity is invalid or being rebuilt, Currently it says emulated.
Let me know if I should remove multi-lang or add to others and status if you think should be something different to rebuild or invalid.
Made the same change on my 6.9.2 server as its currently rebuilding parity.
> Change Dashboard Parity status to be invalid and not emulated.

- plugins/dynamix.vm.manager/include/VMMachines.php
- plugins/dynamix.vm.manager/include/libvirt.php
Please find a PR for review to add IP addresses to the VM Manager page. Function is dependant on guest agent being installed on the guest.
Information is added as part of the disk information drop down.  Here is the new view on my test system. Let me know if you would like anything to be changed.
> Show IP on VM Manager VM Page

- plugins/dynamix.docker.manager/include/DockerClient.php
On the icons a fail to download previously would never return a "false", but would have the file with contents of "404: Not Found" FAILONERROR true fixes this
> Log docker icon download failures

- plugins/dynamix.docker.manager/include/DockerClient.php
re: https://forums.unraid.net/bug-reports/prereleases/610rc5-r1846/
Caused by previous versions of CA adding an Icon reference that isn't valid under rc5+
> Docker: Ignore icon references to default question mark

- languages/en_US/helptext.txt
- plugins/dynamix.vm.manager/VMSettings.page
- plugins/dynamix.vm.manager/include/libvirt.php
- plugins/dynamix.vm.manager/include/libvirt_helpers.php
- plugins/dynamix.vm.manager/templates/Custom.form.php
- plugins/dynamix.vm.manager/templates/LibreELEC.form.php
- plugins/dynamix.vm.manager/templates/OpenELEC.form.php
This PR gives the user the option of using LibVirt networks in addition to bridges without having to edit the VM's XML.
I tested the changes locally on my Unraid and so far have not found any errors.
Example of a tested network:
```
<network>
<name>sriov0</name>
<uuid>bbb1fc77-0d0e-45c9-b577-597ac9d4792c</uuid>
<forward mode='hostdev' managed='yes'>
<pf dev='eth3'/>
<address type='pci' domain='0x0000' bus='0x81' slot='0x10' function='0x1'/>
<address type='pci' domain='0x0000' bus='0x81' slot='0x10' function='0x2'/>
<address type='pci' domain='0x0000' bus='0x81' slot='0x10' function='0x3'/>
...
</forward>
</network>
```
> feat: make libvirt networks accessible via gui

- plugins/dynamix/DeviceCapabilities.page
- plugins/dynamix/include/SmartInfo.php
Please find PR for adding NVME capabilities to the Disk Capabilities page.
I have only one NVME so have not been able to do extensive testing.
This is the view for a NVME drive.
Existing view for SATA
Smartctl output.
`root@computenode:/usr/src# smartctl -n standby -c  /dev/nvme0 
smartctl 7.3 2022-02-28 r5338 [x86_64-linux-5.18.14-Unraid] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF INFORMATION SECTION ===
Firmware Updates (0x12):            1 Slot, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x005e):     Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat Timestmp
Log Page Attributes (0x0e):         Cmd_Eff_Lg Ext_Get_Lg Telmtry_Lg
Maximum Data Transfer Size:         64 Pages …
> Add nvme capabilities

- plugins/dynamix.docker.manager/include/DockerClient.php
Add a new dockerman system label net.unraid.docker.shell to allow specifying what shell to use for the console link via labels.
Nominal values would be 'sh' or 'bash'.
This will allow containers not created by dockerman to still specify a shell for the webui
> Dockerman add ability to specify shell with container label.

- plugins/dynamix/include/NotificationAgents.xml
Discord will not allow links with bare hostname, links must have both hostname and tld or no link at all
> fix: Discord notification agent url

- plugins/dynamix.vm.manager/include/libvirt.php
- plugins/dynamix.vm.manager/include/libvirt_helpers.php
- plugins/dynamix.vm.manager/templates/Custom.form.php
- plugins/dynamix.vm.manager/templates/LibreELEC.form.php
- plugins/dynamix.vm.manager/templates/OpenELEC.form.php
Add Missing USB devices on list so can be removed from VM. 
Add startupPolicy fields to USB list for future updates.
These are the options available to startupPolicy 
For the GUI input it can be a select drop down for each of the values.
or as per the feature request just add a check box for the optional option which I think will be the better option as the requisite option is unlikely to be used.
Link to feature request:
https://forums.unraid.net/topic/127949-support-for-adding-optional-usb-devices-in-vm-manager-form-view/#comment-1165862
Used checkbox option in PR.
> Add Missing USB support

- plugins/dynamix.plugin.manager/scripts/plugin
- plugins/dynamix/ParityCheck.page
- plugins/dynamix/include/update.parity.php
Fix post hook failure when plugin download fails.  Php reserved characters were being passed in the $error string to the post_plugin_check causing it to fail.
> Fix post hook failing when plugin download fails; default scheduled parity check to non correcting.

- plugins/dynamix/ParityCheck.page
- plugins/dynamix/include/update.parity.php
The legacy setting for 'write' was 'NOCORRECT' for non-correcting parity check.  The new logic uses 'yes' and 'no' for the setting.  'NOCORRECT' is now made into a 'no' to respect the legacy setting.
> Change to be sure legacy 'write' setting in dynamix.cfg  is respected.

- plugins/dynamix/ParityCheck.page
- plugins/dynamix/default.cfg
My original attempt to fix the default parity check was pretty much a disaster.  This cleans that up.  All I had to do was set the write="NOCORRECT" in the default.cfg file and set the non-correcting as the first selection.  Duh!!
> Redo my failed attempt at defaulting to non-correcting parity check.

- plugins/dynamix.vm.manager/include/VMMachines.php
- plugins/dynamix.vm.manager/include/libvirt.php
Change to use libvirt_domain_interface_addresses which has been available for a long time but was not documented in the API manual. Using this function stops tainted warnings being written to the log.
Domain id=4 is tainted: custom-ga-command will no longer be seen in the log.
> Change to use API

- plugins/dynamix.vm.manager/include/libvirt.php
- plugins/dynamix.vm.manager/include/libvirt_helpers.php
- plugins/dynamix.vm.manager/templates/Custom.form.php
If you enable copy paste you need to install additional software on the client in addition to the QEMU agent if that has been installed. https://www.spice-space.org/download.html is the location for spice-vdagent for both window and linux. Note copy paste function will not work with web spice viewer you need to use virt-viewer.
> Enable copy paste option for virtual consoles

- plugins/dynamix.vm.manager/templates/Custom.form.php
- plugins/dynamix.vm.manager/templates/LibreELEC.form.php
- plugins/dynamix.vm.manager/templates/OpenELEC.form.php
If mac address is blanked on template it will remove NIC. But you cannot add back in from the template only via XML editior. This PR allows new MAC to be created to add back the NIC.
> Fix for missing NIC option

- plugins/dynamix.vm.manager/include/libvirt.php
VM Manager page doesn't load if PCI devices are missing due to issue with libvirt_nodedev_get_information.
> FixPCIDevice Lookup

- plugins/dynamix.plugin.manager/include/ShowPlugins.php
I could've sworn something like this went into 6.7 but obviously wrong
> Plugin: Don't show update button if incompatible

- plugins/dynamix.plugin.manager/scripts/plugin
Sometimes I see percentages like `20230330%` on the plugin install screen during download. And i wondered why...
I saved the example wget output and tested the [regex](https://github.com/limetech/webgui/blob/8a0546ad7c78821083d6aec3a6a15ada13ebade7/plugins/dynamix.plugin.manager/scripts/plugin#L242) against it. Turns out, that the output contains:
```
Credential=AKIAIWNJYAX4CSVEH53A%2F20230330%2Fus-east-1%2Fs3%2Faws4_request
```
You see the percentage sign? It matches!
So I took a look to the wget out with the right percentage (`0K .......... .......... 100% 7.88M=0.003s`). before and after are always whitespaces, so I changed the regex accordingly: https://regex101.com/r/RhlZji/1
Thats worked.
I put it all together with a final trim to remove the whitespaces before dealing with it …
> Make wget percentage detection more robust

- languages/en_US/helptext.txt
- plugins/dynamix.vm.manager/VMSettings.page
- plugins/dynamix.vm.manager/include/VMMachines.php
- plugins/dynamix.vm.manager/include/VMajax.php
- plugins/dynamix.vm.manager/include/libvirt.php
- plugins/dynamix.vm.manager/javascript/vmmanager.js
- plugins/dynamix/include/DashboardApps.php
Remove lock posix and flock from virtiofsd options as QEMU V8 has dropped virtiofsd and the rust version need to be used going forwards but does not support these options.
https://gitlab.com/virtio-fs/virtiofsd/-/releases
Add support to start remote-viewer from the context menus. This will download a .vv file and if set in the browser will load remote-view will the .vv file.
Please review and let me know any feedback.
> VM Manager Updates

- emhttp/plugins/dynamix/scripts/show_interfaces
- etc/rc.d/rc.apcupsd
- etc/rc.d/rc.avahidaemon
- etc/rc.d/rc.inet1
- etc/rc.d/rc.library.source
- etc/rc.d/rc.nfsd
- etc/rc.d/rc.nginx
- etc/rc.d/rc.ntpd
- etc/rc.d/rc.php-fpm
- etc/rc.d/rc.rpc
- etc/rc.d/rc.samba
- etc/rc.d/rc.sshd
Library file is imported by each rc script, which has the common functions This makes maintenance easier
@Limetech: need a symlink for /etc/rc.d/rc.library.source -> /usr/local/etc/rc.d/rc.library.source
> rc scripts: use common library source

- etc/rc.d/rc.docker
I noticed a bug in the rc.docker script in 6.11.5. 
I'm running my Docker containers in a custom network `br1` with static IPv4 and IPv6 addresses. I have the addresses added in the "Fixed IP address" field. 
That worked just fine when creating a new container and starting it through that view, or when editing a container. However, after disabling and re-enabling Docker, or after rebooting the server, I noticed that my containers didn't autostart and starting them through the GUI also failed. I had to edit them and re-apply the config to make them start. 
Reading through the rc.docker script, I found the bug that causes this: I had the IP addresses (one IPv6, one IPv4) seperated by spaces, not by commas. When creating a container this works just fine, but when the system starts the …
> rc.docker: Fix multiple fixed IPs

- emhttp/plugins/dynamix/scripts/reload_services
- etc/rc.d/rc.library.source
- etc/rc.d/rc.nfsd
- etc/rc.d/rc.nginx
- etc/rc.d/rc.rpc
- sbin/create_network_ini
1. NFS - fix service reload
2. RPC - fix service reload
3. NGINX - remove HTTPS port in FQDN redirect when default 443
4. All services - register IPv4 Link local assignment (169.254.xxx.xxx)
5. All services - make lock file programmable
> RC services update

- emhttp/plugins/dynamix.vm.manager/include/VMajax.php
Remove the .vv file when remote view is used. Otherwise it is left in downloads.
> Add fix to remove downloaded .vv file when used.

- emhttp/plugins/dynamix/styles/default-black.css
- emhttp/plugins/dynamix/styles/default-white.css
When overflow-x is set to 'scroll',
in some browsers, it will reserve
space for the scrollbar and will
override the background color even
when no scrollbar is necessary.
> CSS: set overflow-x to 'auto'

- emhttp/plugins/dynamix/scripts/diagnostics
- remove GitHub user and token from LXC diagnostics if they are set <- this is a upcoming feature for third party image downloads
> update LXC diagnostics

- emhttp/plugins/dynamix.vm.manager/scripts/libvirt_init
- etc/rc.d/rc.inet1
- etc/rc.d/rc.inet2
- etc/rc.d/rc.library.source
- etc/rc.d/rc.local_shutdown
- etc/rc.d/rc.mcelog
- etc/rc.d/rc.nfsd
- etc/rc.d/rc.ntpd
- etc/rc.d/rc.php-fpm
- etc/rc.d/rc.rpc
- etc/rc.d/rc.samba
- etc/rc.d/rc.serial
- etc/rc.d/rc.sshd
- etc/rc.d/rc.udev
- sbin/create_network_ini
- sbin/mount_image
- sbin/vfio-pci
Any shell scripts that have been modified for Unraid should have the correct `#!/bin/bash` shebang to aid with linting.
> Set bash shebang on scripts

- emhttp/plugins/dynamix/Syslog.page
- emhttp/plugins/dynamix/scripts/diagnostics
- etc/rc.d/rc.M
This solves three issues:
* mirrored logs are now cleaned up on each boot, rather than growing forever
* mirrored logs from the previous boot are now included in diagnostics
* mirrored logs from the previous boot are now available in the webgui on Tools -> Syslog
> Improved handling of USB-mirrored syslogs

- emhttp/plugins/dynamix/DashStats.page
After an unexpected JS interruption or rapid toggling of visibility settings in the dashboard, dashboard visibility cookies such as the `hidden_content` or `inactive_content` cookies can be left in a broken state by the browser. Such broken cookies then include either unwanted duplicate md5 values, empty or null values (i.e. due to lone leading/trailing delimiters), resulting in problems.
This - at present - breaks the entire functionality of the affected cookie and results i.e. in unwanted showing/expansion of set to hidden/collapsed dashboard panels. Such broken cookies can - at present - not be recovered from, they need to be removed or expire in order for the user's dashboard visibility settings to function normally and be respected in the dashboard again.
This PR accounts for such …
> Fix browsers leaving dashboard visibility cookies in malformed state

- etc/rc.d/rc.M
This allows to create custom config files for rsyslog in `/boot/config/rsyslog.d/` and link them on boot in the directory `/etc/rsyslog.d/`
> Custom rsyslog config files

- etc/rc.d/rc.S
- detect if boot device is btrfs or fall back to vfat
- set discard=async for btrfs
- correct permissions for NONVFAT boot after bzfirmware is mounted
> Initial btrfs boot device support

- emhttp/plugins/dynamix.vm.manager/include/libvirt.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
Setting keymap to No Keymap should allow the keys to be sent directly to vm for languages without qemu keymaps.
> Add option for no keymap.

- emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
- emhttp/plugins/dynamix.vm.manager/include/VMajax.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
- emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
- emhttp/plugins/dynamix/include/SmartInfo.php
Add storage override to specify where images are created at add VM.
Default will use existing processing. User can specify other option per disk. Override action is only if auto is used..
Metadata stores storage name.
`  <metadata>
<vmtemplate xmlns="unraid" name="Linux" icon="linux.png" os="linux" storage="disk1"/>
</metadata>`
Option to select override is only on Add VM
Change option is disabled.
> Add storage override option

- etc/rc.d/rc.S
- Use first partition for btrfs and xfs boot, this allows a btrfs mirror to boot
- Use `degraded` for btrfs mount to allow boot from degraded btrfs pools
> Fix for btrfs and xfs boot

- emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
- emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
When downgrading if the VM template has been updated to the latest QEMU machine type it will not be found. It will default to i440fx which can create an issue if the machine was Q35.
This PR finds latest current version for a given machine type.
> 6.12 Fix for downgrade

- emhttp/plugins/dynamix/include/SmartInfo.php
I've noticed that (at least some) SAS HDDs report their 'Power on time' SMART attribute in a way that isn't displayed coherently in the Unraid webui.
See this link for a screenshot of current state: https://forums.unraid.net/topic/147041-feature-request-additional-smart-data-for-sas-ssds/?do=findComment&comment=1320371
The data returned by smartctl is: `Accumulated power on time, hours:minutes 27979:25` which gets displayed in a misleading way as:
```
Accumulated power on time, hours            minutes 27979
```
This PR fixes this so it now displays properly as:
```
Accumulated power on time                   27979 (3y, 2m, 9d, 19h)
```
> Fix display of 'Accumulated power on time, hours:minutes xxxxx:yy' SMART attribute

- emhttp/plugins/dynamix/include/SmartInfo.php
This PR adds a new 'SSD endurance remaining' indicator (%) to the bottom of the SMART Attributes page for NVMe/SATA/SAS SSDs.  This is useful for a quick at-a-glance indication of SSD health without requiring extra cognitive load and parsing various mfg. specific attributes.  Additionally, (most?) SAS SSDs and some SATA SSDs don't even currently display any attributes that could be used to determine this, requiring the user to resort to the command line to look it up.  More information here: https://forums.unraid.net/topic/147041-feature-request-additional-smart-data-for-sas-ssds/
For NVME SSDs, this uses the inverse of the `Percentage Used` attribute that is already reported.
For SATA and SAS SSDs, this uses the special smartctl command (`smartctl -l ssd <dev>`) that can return …
> Add 'SSD endurance remaining' SMART Attribute.

- emhttp/plugins/dynamix/include/SmartInfo.php
Many SSDs report how many bytes have been written to and/or read from the flash using some combination of:
* Total_LBAs_Written
* Total_LBAs_Read
* Host_Writes_32MiB
* Host_Reads_32MiB
* TLC_Writes_32MiB
The raw value is a bit hard to grok at a glance, so this PR adds in the calculated KB/MB/GB/TB values (similar to how Power on hours is modified to show years/months/days).
Before:
```
241 | Total lbas written | 0x0032 | 099 | 099 | 000 | Old age | Always | Never | 86530637427
...
241 | Host writes 32mib | 0x0000 | 100 | 100 | 000 | Old age | Offline | Never | 18546
242 | Host reads 32mib | 0x0000 | 100 | 100 | 000 | Old age | Offline | Never | 9189
245 | TLC writes 32mib | 0x0000 | 100 | 100 | 000 | Old age | Offline | Never | 12764
```
After:
```
241 | Total lbas written | 0x0032 | 099 …
```
> Display KB/MB/GB/TB written in SMART Attributes for SSDs

- emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
- emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
Custom Docker registries may be hosted on non-standard-ports [1]. Images stored in such a registry can be used in Unraid by providing a "repository" name such as "my.registry.dev:5002/myproject/myservice:latest".
However, the Docker GUI of Unraid does not properly support such image names, because it wrongly assumes that an image may only ever contain one ":" character.
This PR provides a rewritten version of `DockerUtil::ensureImageTag` that properly handles image names that contain custom registries with a port specification. This includes all existing "magic" additions (like prefixing images with "library/" if necessary, and adding ":latest" if missing).
Furthermore, a new method `DockerUtil::parseImageTag` is introduced, which properly splits an image name into "strRepo" and "strTag", …
> Docker: Allow custom registry with a port specification

- emhttp/plugins/dynamix/scripts/diagnostics
Pending Larry approval
Runs FCP scan if one hasn't been already run within 24 hours.  (FCP by default logs issues in syslog.  If user does disable logging then FCP still logs "issues found, but not logged due to user choice)
> DRAFT Run FCP scan during diagnostics

- etc/rc.d/rc.docker
> Backport: Docker: fix WG routes added to the correct interface

- emhttp/plugins/dynamix.vm.manager/include/VMMachines.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
- emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
Fix to not set type to raw on update.
New vdisks with type qcow2 will be created as .qcow2
If a qcow2 disk is set with a .img file name it will show as manual in the gui.
> Fixes for QCOW2 images

- emhttp/plugins/dynamix/include/DefaultPageLayout.php
Override it (ie: automatically close the window) so that CA can carry on with installing / updating plugins without waiting for user intervention
> Backport: Allow CA to override the "DONE" button appearing during multi installs / updates

- emhttp/plugins/dynamix/HelpButton.page
- emhttp/plugins/dynamix/include/DefaultPageLayout.php
Pet peeve that if a user clicks help then it stays selected from page to page.  Make the user instead reselect help as they navigate
We still get users posting "How do I get rid of the blue boxes" ~ once per month
Up to Larry
> Don't save state of help button from page to page

- emhttp/plugins/dynamix/include/DefaultPageLayout.php
Override it (ie: automatically close the window) so that CA can carry on with installing / updating plugins without waiting for user intervention
> Allow CA to override the "DONE" button appearing during multi installs / updates

- emhttp/plugins/dynamix.vm.manager/include/libvirt.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
- emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
Add flag to vdisks to allow disks to show in guest as ssd rather than a hdd.
XML after setting flag.
> Add SSD flag for vdisks.

- etc/rc.d/rc.S.cont
- Remove tmpfs for cgroup2 mount
- Change source from `none` to `cgroup2`
- Add mount options nosuid, nodev, noexec, relatime, nsdelegate, memory_recursiveprot for more security
- Display message if /sys/fs/cgroup does not exist instead of creating a unusual mount
> Update cgroup2 mount

- emhttp/update.php
A php warning occurs when a text area is to be saved to a file and it contains a reserved php character.  Update.php tries to parse the file and extract a specific section even if the file is only to be saved.  It is also trying to extract a section when the $section is not defined i.e. $section is set to false.
> Fix php warning when saving text to a file.

- emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
- emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
Remove the update/force update buttons from the GUI for non dockerman containers.  Pressing them results in an error and updates for these containers should be done by the appropriate manager.
> Remove update buttons for non-dockerman containers

- emhttp/languages/en_US/helptext.txt
- emhttp/plugins/dynamix/SyslogSettings.page
- emhttp/plugins/dynamix/scripts/rsyslog_config
I've tried using the built-in Syslog server in UnRAID and found two issues: 
A) the HTML input field for the syslog server is limited to 23 characters, my hostname is longer. I increased it to 50 and it works fine.
B) as stated [on the forums](https://forums.unraid.net/topic/150195-unraid-syslog-server-use-device-name-for-filename-instead-of-ip/), I don't like how UnRAID adds the client's IP address to the syslog file name. 
Some clients may switch between IPv4 and IPv6, or they have IPv6 privacy extensions, or they switch between different IPv6 networks. All of which will result in tons of different logfiles for each client. 
To work around this issue, I added a new config field that allows people to enter a template for the syslog file name instead of hardcoding it to …
> Add syslog filename support

- emhttp/plugins/dynamix.my.servers/include/state.php
This fixes an error a specific subset of users may be experiencing – see https://forums.unraid.net/topic/154030-6128-log-spammed-with-references-to-unraid-apiphp/
If a user previously had a historic Unraid Connect / My Servers installed and was signed in, then eventually removed the plugin without explicitly signing out first there could have been an instance where the `myservers.cfg` may not have been cleared / removed. (Note that the plugin clears the cfg file…don't know the specific version where that was introduced)
Our file to serve the web components the server details was not correctly configured to handle this instance.
So because the myservers.cfg file may have Unraid.net account details in it the webgui web components were assuming it should be calling the `unraid-api` to keep …
> fix: state connect values without connect installed [6.12]

- emhttp/plugins/dynamix.my.servers/include/state.php
This fixes an error a specific subset of users may be experiencing – see https://forums.unraid.net/topic/154030-6128-log-spammed-with-references-to-unraid-apiphp/
If a user previously had a historic Unraid Connect / My Servers installed and was signed in, then eventually removed the plugin without explicitly signing out first there could have been an instance where the `myservers.cfg` may not have been cleared / removed. (Note that the plugin clears the cfg file…don't know the specific version where that was introduced)
Our file to serve the web components the server details was not correctly configured to handle this instance.
So because the myservers.cfg file may have Unraid.net account details in it the webgui web components were assuming it should be calling the `unraid-api` to keep …
> fix: state connect values without connect installed [6.13]

- emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
If docker comms fail, return (empty) array (as expected by everyone) instead of null. Fixes `foreach() argument must be of type array|object, null given`
> Fix `getDockerJSON`

- emhttp/plugins/dynamix/DeviceInfo.page
- emhttp/plugins/dynamix/DiskSettings.page
There are some new devices since this page was last updated in the webgui, so I've gotten started with adding the ones that are available in version 7.3 (included with unraid 6.12, which I am using). I can't test all the flags as I don't have all of these devices available, but I can confirm that it does indeed work on my device using the flags added for the one device type I needed.
Hope this gets you started with getting this added into future versions!
> Add additional USB device passthrough smartmontools options to webgui

- emhttp/plugins/dynamix/ShareEdit.page
- emhttp/plugins/dynamix/ShareList.page
- emhttp/plugins/dynamix/include/DiskList.php
- emhttp/plugins/dynamix/include/ShareList.php
The total array free space was used, instead of the smallest array disk device free space.  A validity check added to limit the manually entered share floor to less than the free space of the disk with the least free space.  This preents the situation where a share is added and the auto calculated share floor or manually entered share floor does not cause failures in adding shares.
The detection of the situation where no unmountable disks are available when adding shares has been modified to account for unassigned disk slots.
> Fix share floor calculation when the share is array only; fix detection of no mountable devices when adding shares

- emhttp/plugins/dynamix.apcupsd/include/UPSstatus.php
- emhttp/plugins/dynamix/nchan/ups_status
This is a behaviour fix for my prior merged PR, #1743.
My original intention was to try and mirror the default Unraid GUI behaviour on how it reports the UPS statistics, in which @johnnieblack-JorgeB kindly later shared how a traditional UPS that _does_ report `NOMPOWER` behaves and demonstrated how my implementation differs.
This PR is just to bring the behaviour inline with a UPS that _does_ report `NOMPOWER`, so that the GUI is consistent in what and how it reports UPS data, whether you have a UPS that reports `NOMPOWER` or you are using the nominal power override provided in #1743.
As the screenshot below demonstrates, the override nominal power value is now read directly into the Nominal Power `$power` field, mirroring the behaviour of a UPS that reports its `NOMPOWER` value. This …
> Behaviour fix for #1743 : "Add in the ability to set a manual UPS capacity override in `dynamix.apcupsd`"

- emhttp/plugins/dynamix/ShareEdit.page
- emhttp/plugins/dynamix/scripts/xfs_check
- xfs check does not show file issues from exit code.
- Remove subpools from the available pool devices in primary and secondary storage in share edit.
> Xfs check not detecting file issues; remove subpools from share edit.

- emhttp/plugins/dynamix/ShareEdit.page
- emhttp/plugins/dynamix/scripts/xfs_check
- Remove debug line left in code.
- Fix incorrect commit of xfs_repair script.  The original concept did not return the proper exit code.
> Remove debug from share edit used for subpools removed from primary and secondary drop downs; fix incorrect commit.

- emhttp/plugins/dynamix/DashStats.page
backport of fix for dashboard hidden/collapsible settings not being remembered due to cookies left in malformed state.
this fix is already present in _master_ (#1472), but here's a backport for 6.12 as it's a simple enough fix for this real annoyance.
-- Rysz
> backport: clean up visibility cookies left in malformed state

- etc/rc.d/rc.docker
- override filesystem type to overlay2 if `DOCKER_BACKINGFS` in docker.cfg is set to `overlay2`
> Initial Docker overlay2 support

- emhttp/plugins/dynamix/DashStats.page
same as #1472 and #1776 just now for sanitizing the tile ordering cookies as well
if the browser leaves cookies in a malformed state (with null, empty or duplicate md5s) the tile ordering is not remembered
this PR cleans up the cookies (as already done with the hidden & inactive tile cookies) so tile sorting does not fail in such cases
--Rysz
> fix table order breaking when cookie is left malformed

- emhttp/plugins/dynamix.apcupsd/UPSdetails.page
When either of the UPS config options `Battery level to initiate shutdown (%)` or `Runtime left to initiate shutdown (minutes)` are set to empty, the UPS details section breaks. This is due to the `getUPSstatus` function passing values directly from the config, which results in an error if either value is empty.
The fix sets and passes variables to the `getUPSstatus` function for each of the config options. The variables are either set to the value contained in the config file, or `0` if the config has no value set.
Tested the fix locally and confirmed it functions as expected.
> Fix UPS settings page when config contains empty values

- emhttp/update.php
When execution is done (EOF), might be good practice to attempt releasing the now unused file pointer back to the system.
Just checked the rest of the repository and it seems to be done everywhere else like this, was probably just forgotten here.
-- Rysz
> update.php: release file pointer after usage

- emhttp/update.php
#1809 backported for 6.12
_When execution is done (EOF), might be good practice to attempt releasing the now unused file pointer back to the system.
Just checked the rest of the repository and it seems to be done everywhere else like this, was probably just forgotten here._
_-- Rysz_
> (backport) update.php: release file pointer after usage

- emhttp/plugins/dynamix.docker.manager/DockerContainers.page
- emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
- emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
- emhttp/plugins/dynamix.docker.manager/include/Helpers.php
This PR aims to improve how networks are displayed for docker containers.
- fix where network ID instead of a name is displayed (generally for docker compose created containers).
- display multiple networks and the associated IP for each
> Network info display improvements

- emhttp/plugins/dynamix.vm.manager/VMSettings.page
- emhttp/plugins/dynamix.vm.manager/include/VMajax.php
- Make VM Settings work again when using GRUB
- Make sure to properly inject/remove `PCIe ACS override`/`VFIO allow unsafe interrupts` to `grub.cfg`
> Grub VM settings fix

- emhttp/plugins/dynamix/include/.login.php
- emhttp/plugins/dynamix/include/.set-password.php
This replaces the two uses of document.write with a more modern solution. First we create the content needed in the body. Then wipe the body content out and finally append the desired content to it.
This does NOT fix the [3rd referenced use](https://github.com/limetech/webgui/blob/d7982ce3e072d5c86d5f4ce79e5da29e5f7838db/plugins/dynamix.vm.manager/novnc/app/error-handler.js#L58) in the app code. Since it is from the VNC module, we'd be diverging from upstream which would make updating the VNC client more difficult in the future unless we rember to always go patch that again. To fix that, we should work upstream to have a solution in their system. There are also a few more findings of `document.write` elsewhere in the app code that is tracked. Same situation as this one for all of them, …
> fix: replace document write usages

- emhttp/plugins/dynamix/UserEdit.page
This follows up the changes from #1127 to allow for more modern SSH key types. This changes the regex to the one provided for [combined support for all key types](https://github.com/nemchik/ssh-key-regex?tab=readme-ov-file#support-all-known-key-types-less-secure). If support for restrictions to the more secure key types only is desired, I think that needs a discussion on adding a "Hardened Mode" setting somewhere that may also impact other parts of the system too, instead of just SSH key formats.
This fixes an issue where current modern keys are being rejected by the web interface. Such as fresh keys generated with [Secretive](https://github.com/maxgoedjen/secretive) where users don't have control over which type of encryption is used.
> feat(user-edit): update allowed ssh key encryptions

- emhttp/plugins/dynamix/PHPsettings.page
**TLDR:** Setting the PHP error reporting level to "Default" in the GUI does not restore the respective boot-time default state, but deletes the configuration file, which causes any PHP events to be shown on screen and GUI elements/plugins to break. This PR fixes that bug and makes the GUI "Default" for PHP error reporting level consistent with that of the OS boot-time defaults.
**At boot-time the OS installs the following sane PHP error reporting level defaults**:
```
root@TowerOLD:~# cat /etc/php.d/errors-php.ini
error_log="/var/log/phplog"
display_startup_errors="0"
display_errors="0"
log_errors="1"
error_reporting=E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED
```
**Setting a different PHP error reporting level through the GUI and then setting it back to "Default" (in the GUI):**
``` …
```
> fix inconsistent PHP error reporting defaults (PHPSettings.page)

- emhttp/plugins/dynamix/PHPsettings.page
**backport:** fixes bug/inconsistencies between OS defaults and GUI defaults for PHP error reporting
see #1829 for details
in my opinion worth backporting because the GUI default currently creates a hard to diagnose situation where the dashboard will break if PHP events of any kind occur and are printed on the screen (or in backend responses) due to the bug/issue described.
-- Rysz
> (backport) fix inconsistent PHP error reporting defaults (PHPSettings.page)

- emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
- emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
This commit ensures containers with multiple networks are always displayed. Previously, networks connected to containers (docker network connect...) don't show
This is an improvement on #1616
> Network info display improvements (part 2)

- emhttp/plugins/dynamix.vm.manager/include/libvirt.php
- emhttp/plugins/dynamix.vm.manager/include/libvirt_helpers.php
- emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
Add support for unmap by adding discard='unmap' if type is file and either of these bus types. Virtio,SCSI or SATA
Example XML
`<disk type='file' device='disk'>
<driver name='qemu' type='raw' cache='writeback' discard='unmap'/>
<source file='/mnt/vmpoolzfs/domains2/Linuxxxy/vdisk1.img'/>
<target dev='hdc' bus='virtio'/>
<serial>vdisk1</serial>
<boot order='1'/>
<address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
</disk>`
> Add Unmap Support

- emhttp/update.php
Right now there is only one method to define default values for a form with user settings within the WebGUI and plugins.
All default values need to be put into a single `default.cfg` file, which can get messy if a page or plugin has multiple forms.
This PR adds two more methods to define default values, so UI developers can be more flexible when using multiple forms.
**The default behaviour remains unchanged**, but two more options are added for better logical separation of defaults values.
I'm sure these optional additions (default behaviour remains unchanged), would be appreciated by our UI/plugin developers.
It should make it much easier to streamline defining default values for user setting forms, to avoid issues like #1829 .
- **Additional documentation added to _update.php_ …
> update.php: add two optional methods to define defaults

- emhttp/plugins/dynamix/include/OpenTerminal.php
Added function getUserShell() to OpenTerminal.php and use it for the execution
> Feature Request: Use user's actual shell in OpenTerminal.php #1832

- emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
This is just a small fix to make sure internal IPs from stopped containers are not displayed.
Before:
After:
> Make sure to not show internal IP from stopped containers

- emhttp/plugins/dynamix.docker.manager/include/DockerClient.php
- emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php
Show containers which are created not by Unraid (either via the Compose plugin, Portainer running on Unraid, directly via `docker run`, or any other 3rd party method) and which are not labeled to be managed through dockerman.
- Hide Autostart switch from 3rd party containers
- Show that an update is available but don't allow updates (due to 3rd party software)
- Show the Stack name if the containers are created by the Docker Compose plugin
The following are just pictures to demonstrate how that will look like:
The first container is created by Portainer
The second container is created by the Docker Compose plugin
The other containers are created by Unraid through the CA App or through the `Add Container` button
> Correctly identify/show non dockerman Managed containers

- emhttp/plugins/dynamix/nchan/parity_list
- Change poll inrterval to 3 seconds.  There is no reason to poll every second.
- Remove latest parity check files on the next poll after the parity history is updated.  I believe there was a race condition here with the 'monitor' task that sends the notify message.  It was picking up the previous parity history entry and not the current parity check.
- Change 'file_put_contents()' to 'file_put_contents_atomic()' wrapper.  Cannot do this for a file_put_contents file append though.
> Parity check wrong again.

- emhttp/plugins/dynamix/include/PageBuilder.php
- make sure the maximum icon size for a plugin is 18x18px
This PR fixes an issue when a plugin maintainer uses a .png as icon file instead of the default Font Awesome ones.
Current implementation with a 500x500px png:
With the changes from the PR:
> Fix issue with plugin icons

- etc/rc.d/rc.nginx
This change updates rc.nginx to pass path info to CGI scripts.
This change was initially considered via #1421. Instead of applying the change globally, the change was implemented via the Tailscale plugin patching rc.nginx during Tailscale startup (dkaser/unraid-tailscale-utils@d572961). Per #1421, we planned to evaluate making this a global change after ensuring that it does not have any harmful side effects.
The Tailscale plugin has been applying this change since release 2023.09.14 and is currently in use by at least 11,500 Unraid servers. In this time, there have been no reports of any issues that have been related to the addition of fastcgi_path_info.
> Add fastcgi_path_info to default nginx configuration

- emhttp/plugins/dynamix/include/SysDevs.php
tests for exec-returned variable/line existence before usage.
fixes PHP warnings on "System Devices" page encountered under some circumstances:
```
PHP Warning:  Undefined array key 0 in /usr/local/emhttp/plugins/dynamix/include/SysDevs.php on line 94
PHP Deprecated:  preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated in /usr/local/emhttp/plugins/dynamix/include/SysDevs.php on line 94
```
-- Rysz
> dynamix/include/SysDevs.php: fix PHP warnings

- etc/rc.d/rc.sshd
This ensures that only the sshd PIDs from the host are terminated, and it also resolves an issue where an sshd service inside a container might automatically restart if it gets killed, which would prevent sshd on the host from starting. 
The current implementation kills all sshd daemons regardless of whether they are running in a Docker container or an LXC container.
> Only kill sshd from host

- etc/rc.d/rc.docker
- Fix error in first if condition which always returned `false`
- Change name from variables so that it a bit easier to read
- Make sure that custom interfaces with a higher index then 0 are properly rebuilt
> Fix for rc.docker for interfaces with higher index than 0

- emhttp/plugins/dynamix/include/RoutingTable.php
This change allows the Network Settings page to display routes from all routing tables, not just the default one.
In particular, Tailscale does not use the default routing table when adding routes. Instead, it adds routes to a separate table (route table 52) and then creates a network rule to process that table in addition to the default table. The existing Network Settings logic only polls for routes on the default table. and as a result routes added by Tailscale do not appear.
This change specifically excludes items in the local routing table, which is maintained by the kernel and contains routes for the local system. Displaying these routes would create unnecessary noise in the route display.
> feat: show routes from all routing tables, not just default

- emhttp/plugins/dynamix/scripts/diagnostics
Sanitize ts.net domain names found in servers.conf.txt since these could potentially be used for remote access similar to myunraid.net domains.
> feat: sanitize ts.net domain names from nginx config

- emhttp/plugins/dynamix.docker.manager/DockerSettings.page
- store path outside from function to not shorten path if users switches multiple times between `image` and `folder`
- make sure overlay2 is selected by default
> Fix for docker directory

- emhttp/plugins/dynamix/ShareEdit.page
When a secondary pool device is missing and the Array is chosen for the primary device, the configuration would fail because the secondary device is still believed to be a missing pool device.
> Fix a situation where the secondary pool device is missing.

- etc/rc.d/rc.ntpd
Change to use interface rather than IP.
From
interface ignore wildcard
interface ignore ipv6
interface listen 192.168.1.225 # br0
server time1.google.com iburst
server time2.google.com iburst
server time3.google.com iburst
server time4.google.com iburst
to
interface ignore wildcard
interface ignore ipv6
interface listen br0 # 192.168.1.225
server time1.google.com iburst
server time2.google.com iburst
server time3.google.com iburst
server time4.google.com iburst
> Set NTP to use interfaces.

- emhttp/plugins/dynamix/include/ShareList.php
- When checking for an empty share, any '*.DS_Store' files are ignored and not included in the share empty check.
- Delete all '*.DS_Store' files when deleting the share.
> Delete all '*.DS_Store' files when deleting share.

- etc/rc.d/rc.rsyslogd
bugfix: multiple running _rsyslogd_ processes (e.g. spawned by Docker containers) caused the _rc.d_ script to think that the OS-native process was already running, resulting in startup or restart failure of the OSes daemon. the proposed changes make the script act on the OS-native PID file and not other unrelated processes by name.
-- Rysz (credits to Discord user _Brendann_ for noticing this issue)
> (bugfix) /etc/rc.d/rc.rsyslogd: OS-native PID for decisions

- emhttp/languages/en_US/helptext.txt
- emhttp/plugins/dynamix/SecuritySMB.page
- Add warning to SMB security setting on shares about Windows Security Signing.
- Add help text to SMB security setting on shares about Windows Security Signing.
- Add help text abuot upgrading ZFS pools to device info page.
- Add help text for zfs scrub to device info page.
> Add warning about server signing to SMB Security page; update helptext.

- emhttp/plugins/dynamix/scripts/feedback
Email is always required now on the feedback form.  The 'Submit' button will be disabled until the text area is filled in and a valid email address is entered.
> Email is now required on feedback form.

- emhttp/plugins/dynamix/include/SysDevs.php
backport of #1854, tests for exec-returned variable/line existence before usage
fixes PHP warnings on "System Devices" page encountered under some circumstances:
```
PHP Warning:  Undefined array key 0 in /usr/local/emhttp/plugins/dynamix/include/SysDevs.php on line 94
PHP Deprecated:  preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated in /usr/local/emhttp/plugins/dynamix/include/SysDevs.php on line 94
```
-- Rysz
> (backport) dynamix/include/SysDevs.php: fix PHP warnings

- etc/rc.d/rc.docker
- Fix error in first if condition which always returned `false`
- Change name from variables so that it a bit easier to read
- Make sure that custom interfaces with a higher index then 0 are properly rebuilt
This directly address [this](https://forums.unraid.net/bug-reports/stable-releases/6124-etcrcdrcdocker-ignores-additional-container-networks-and-cant-auto-start-affected-containers-again-r2694/) issue from the Forums.
~~Still needs to be tested by the user who reported it, I will remove the draft status when it's been tested.~~
> [Backport] - Fix for rc.docker for interfaces with higher index than 0

- etc/rc.d/rc.rsyslogd
backport of #1882 
bugfix: multiple running _rsyslogd_ processes (e.g. spawned by Docker containers) caused the _rc.d_ script to think that the OS-native process was already running, resulting in startup or restart failure of the OSes daemon. the proposed changes make the script act on the OS-native PID file and not other unrelated processes by name.
-- Rysz (credits to Discord user _Brendann_ for noticing this issue)
> (backport) (bugfix) /etc/rc.d/rc.rsyslogd: OS-native PID for decisions

- emhttp/plugins/dynamix.docker.manager/DockerContainers.page
- Tooltip now opens on `hover` and `click` on Desktop browsers
> Fix for tooltipster `click` not working

- emhttp/plugins/dynamix/ShareEdit.page
- emhttp/plugins/dynamix/include/ShareList.php
When a share is setup on a pool with no array, and then the array is enabled, the share list shows 'Array' instead of pool only and share edit does not recognize this as a pool with secondary selections enabled.
> Fix invalid situation where useCache is 'no' when array is enabled.

- emhttp/languages/en_US/helptext.txt
- share/docker/tailscale_container_hook
- add check if `/config` exists
- display warning if detection was not successful
- make helptext more clear for state directory
- add check if script runs as `root`
> Change state directory logic & add `root` check

- emhttp/plugins/dynamix.docker.manager/include/CreateDocker.php
- share/docker/tailscale_container_hook
- Prioritize searching for Exit Nodes through the container before using the Tailscale plugin if installed. This is necessary to display Exit Nodes from Mullvad for specific containers.
> TS Mullvad VPN changes

- emhttp/plugins/dynamix/include/DefaultPageLayout.php
Several issues fixed with this PR:
- Tabbed page mode does not display the previous 'Main' selection on page refresh.
- Sub-pages (like device attributes) does not always start on the first tab.
- Return from sub-pages does not always return to the last selected 'Main' tab.
Plugins like UD do not work well at all.
> Tabbed page mode not working properly.

- emhttp/plugins/dynamix/include/update.wireguard.php
The MTU needs to be set to at least to the wireguard default. While it seems to work just fine, to create a docker bridge with a MTU of 1500, it breaks in some cases. For example, if you "curl https://api.minecraftservices.com/publickeys" via a container thats running over that wireguard-docker-bridge, it fails.
> Set MTU of docker wireguard bridge to match wireguard default MTU

- etc/rc.d/rc.nfsd
rc.nfsd does not stop nfsd. Even after running `/etc/rc.d/rc.nfsd stop` and `/etc/rc.d/rc.rpc stop`, nfsd continues to run.
As a result, changes to `/etc/default/nfs` (e.g., Tailscale interfaces) are never applied.
nfsd cannot be killed using `killall`. Per the [kernel server documentation](https://docs.kernel.org/admin-guide/nfs/nfsd-admin-interfaces.html), knfsd is shut down by setting the number of threads to zero.
> fix: nfsd restarts

- emhttp/plugins/dynamix/nchan/update_1
- Only do 'lsof' command in 'update_1' on disk devices.  There is no need to do the 'lsof' command on UD mount points.  When a UD remote share goes offline, it can hang any 'lsof' commands.
- Add 3 second timeout so 'lsof' will always terminate and not hang.
- The 'lsof' command is used to update the stream count on the Dsshboard page on SMB shares.
> Limit 'lsof' command to valid mount points in /nchan/update_1.

- emhttp/plugins/dynamix/ShareEdit.page
It looks like several previous PRs are showing up again.  I updated my fork, and the Unraid webgui appears to have the previous PRs applied, but GitHub seems to want to apply them again.  Everything checks out on my end.
> Read and Write shares not working.

- emhttp/plugins/dynamix.docker.manager/DockerSettings.page
The "Enable container table readmore-js" is not working properly on some browsers.
> Backport: Docker dropdown not working.

- emhttp/plugins/dynamix/include/FileTree.php
- emhttp/plugins/dynamix/include/ShareList.php
- Allow the remote share mounts to show in the file picker.
- The tool tip on a user share browse showed "%20" instead of a space on a share with a space.
> UD devices not selectable in picker and file manager

- share/docker/tailscale_container_hook
In some cases, line 105 will fail because of SSL verification issues. Namely, that there are no root CAs installed in the container environment. 
```
TAILSCALE_VERSION=$(wget -qO- 'https://pkgs.tailscale.com/stable/?mode=json' | jq -r '.TarballsVersion')
```
Installing `ca-certificates` alongside `wget` and `jq` fixes this problem.
I have tested it on a few images on my Unraid 7 environment that do (`home-asssistant/home-assistant`) and don't (`gristlabs/grist`) have `ca-certificates` present, and have found this fix to be working.
> Install `ca-certificates` during `tailscale_container_hook` operations to prevent SSL errors in some cases

- emhttp/plugins/dynamix.docker.manager/javascript/docker.js
Revert as browser zoom levels (and mobile) can result in the context menu appearing above with the top items rendered off the screen.
Better to not render the last item(s) by always having the menu appear below than the important ones rendered above and unable to select
https://github.com/unraid/webgui/pull/2074
> Backport Fix: Revert allow docker context menus above or below

- emhttp/plugins/dynamix/styles/jquery.sweetalert.css
- Increased max-width of swaltext to 600px for better responsiveness.
- Added styles to ensure p tags without pre children break words to prevent overflow.
> style: prevent default swal overflow

- emhttp/plugins/dynamix/styles/default-base.css
- Added `overflow-x: auto;` to allow unresponsive set width legacy content to scroll horizontally as needed in default-base.css.
> style: enable horizontal scrolling for legacy content

- emhttp/plugins/dynamix/include/DefaultPageLayout.php
- Reverted the banner path from `$config/webGui/banner.png` to `$config/plugins/dynamix/banner.png` to reflect the correct storage location on the boot drive.
> fix: update custom banner path in DefaultPageLayout.php

- emhttp/plugins/dynamix.vm.manager/include/VMedit.php
- emhttp/plugins/dynamix.vm.manager/styles/edit.css
- emhttp/plugins/dynamix.vm.manager/templates/Custom.form.php
- emhttp/plugins/dynamix/styles/default-base.css
Because the VMEdit.php template is custom and doesn't match the dev style of `*.page` files, this makes a refactor for a completely responsive layout extremely difficult and prone to errors.
So a solution, that could easily be used by other templates (especially by plugin authors), is to wrap their content w/ a `Content--non-responsive` class. And this will add a min-width of 1200px, which matches the legacy non-responsve webgui width.
- This PR includes that CSS class on the main wrapper of the VMEdit.php parent wrapper element.
- fix: vm edit cpu width
> feat: vm responsive layout fallback

- emhttp/plugins/dynamix.docker.manager/DockerContainers.page
- emhttp/plugins/dynamix.vm.manager/VMMachines.page
- emhttp/plugins/dynamix/PageMap.page
- emhttp/plugins/dynamix/Processes.page
- emhttp/plugins/dynamix/Syslog.page
- emhttp/plugins/dynamix/Vars.page
- emhttp/plugins/dynamix/include/DefaultPageLayout/BodyInlineJS.php
- emhttp/plugins/dynamix/include/DefaultPageLayout/HeadInlineJS.php
- emhttp/plugins/dynamix/sheets/Syslog.css
When the responsive layout was introduced it caused a regression with the "Listing Height" Display Settings because the copied and pasted JS across the individual pages that made that previously work was using "magic number" pixel values based on a non-responsive / fixed height of various elements.
The new JS function `fillAvailableHeight` is more robust and built in a way that specific elements on the given page can be passed in as arguments and the available height of the target element is then dynamically calculated. With a built in window resize listener the function is only needs to be called once per page that uses it.
> fix: display settings listing height responsive regression
